"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ALLOW_GRACE_PERIOD_KEY = exports.SubscriptionStatusGuard = exports.LicenseGuard = exports.MODULE_METADATA_KEY = exports.getModuleMetadata = exports.RequiresModule = exports.ROLE_METADATA_KEY = exports.getRoleMetadata = exports.RequireAllRoles = exports.RequireRoles = exports.PERMISSION_METADATA_KEY = exports.getPermissionMetadata = exports.RequireAnyPermission = exports.RequirePermissions = void 0;
var permission_decorator_1 = require("./permission.decorator");
Object.defineProperty(exports, "RequirePermissions", { enumerable: true, get: function () { return permission_decorator_1.RequirePermissions; } });
Object.defineProperty(exports, "RequireAnyPermission", { enumerable: true, get: function () { return permission_decorator_1.RequireAnyPermission; } });
Object.defineProperty(exports, "getPermissionMetadata", { enumerable: true, get: function () { return permission_decorator_1.getPermissionMetadata; } });
Object.defineProperty(exports, "PERMISSION_METADATA_KEY", { enumerable: true, get: function () { return permission_decorator_1.PERMISSION_METADATA_KEY; } });
var role_decorator_1 = require("./role.decorator");
Object.defineProperty(exports, "RequireRoles", { enumerable: true, get: function () { return role_decorator_1.RequireRoles; } });
Object.defineProperty(exports, "RequireAllRoles", { enumerable: true, get: function () { return role_decorator_1.RequireAllRoles; } });
Object.defineProperty(exports, "getRoleMetadata", { enumerable: true, get: function () { return role_decorator_1.getRoleMetadata; } });
Object.defineProperty(exports, "ROLE_METADATA_KEY", { enumerable: true, get: function () { return role_decorator_1.ROLE_METADATA_KEY; } });
var requires_module_decorator_1 = require("./requires-module.decorator");
Object.defineProperty(exports, "RequiresModule", { enumerable: true, get: function () { return requires_module_decorator_1.RequiresModule; } });
Object.defineProperty(exports, "getModuleMetadata", { enumerable: true, get: function () { return requires_module_decorator_1.getModuleMetadata; } });
Object.defineProperty(exports, "MODULE_METADATA_KEY", { enumerable: true, get: function () { return requires_module_decorator_1.MODULE_METADATA_KEY; } });
var license_guard_1 = require("./license.guard");
Object.defineProperty(exports, "LicenseGuard", { enumerable: true, get: function () { return license_guard_1.LicenseGuard; } });
var subscription_status_guard_1 = require("./subscription-status.guard");
Object.defineProperty(exports, "SubscriptionStatusGuard", { enumerable: true, get: function () { return subscription_status_guard_1.SubscriptionStatusGuard; } });
Object.defineProperty(exports, "ALLOW_GRACE_PERIOD_KEY", { enumerable: true, get: function () { return subscription_status_guard_1.ALLOW_GRACE_PERIOD_KEY; } });
//# sourceMappingURL=index.js.map