"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.REQUEST_ID_HEADER = exports.CAUSATION_ID_HEADER = exports.CORRELATION_ID_HEADER = exports.openTelemetryApi = exports.startChildSpan = exports.getActiveSpan = exports.withSpan = exports.recordSpanError = exports.setSpanStatus = exports.addSpanAttributes = exports.endSpan = exports.startSpan = exports.shutdownTracer = exports.initializeTracer = exports.CorrelationContextParam = exports.CausationId = exports.CorrelationId = exports.LoggingInterceptor = exports.CorrelationInterceptor = exports.createCorrelationMiddleware = exports.CorrelationMiddleware = exports.correlationStorage = exports.createCorrelationHeaders = exports.injectCorrelationId = exports.extractCausationId = exports.extractCorrelationId = exports.createCorrelationContext = exports.runWithCorrelationContext = exports.getCausationId = exports.getCorrelationId = exports.getCorrelationContext = exports.generateCorrelationId = void 0;
var correlation_id_1 = require("./correlation-id");
Object.defineProperty(exports, "generateCorrelationId", { enumerable: true, get: function () { return correlation_id_1.generateCorrelationId; } });
Object.defineProperty(exports, "getCorrelationContext", { enumerable: true, get: function () { return correlation_id_1.getCorrelationContext; } });
Object.defineProperty(exports, "getCorrelationId", { enumerable: true, get: function () { return correlation_id_1.getCorrelationId; } });
Object.defineProperty(exports, "getCausationId", { enumerable: true, get: function () { return correlation_id_1.getCausationId; } });
Object.defineProperty(exports, "runWithCorrelationContext", { enumerable: true, get: function () { return correlation_id_1.runWithCorrelationContext; } });
Object.defineProperty(exports, "createCorrelationContext", { enumerable: true, get: function () { return correlation_id_1.createCorrelationContext; } });
Object.defineProperty(exports, "extractCorrelationId", { enumerable: true, get: function () { return correlation_id_1.extractCorrelationId; } });
Object.defineProperty(exports, "extractCausationId", { enumerable: true, get: function () { return correlation_id_1.extractCausationId; } });
Object.defineProperty(exports, "injectCorrelationId", { enumerable: true, get: function () { return correlation_id_1.injectCorrelationId; } });
Object.defineProperty(exports, "createCorrelationHeaders", { enumerable: true, get: function () { return correlation_id_1.createCorrelationHeaders; } });
Object.defineProperty(exports, "correlationStorage", { enumerable: true, get: function () { return correlation_id_1.correlationStorage; } });
var correlation_middleware_1 = require("./middleware/correlation.middleware");
Object.defineProperty(exports, "CorrelationMiddleware", { enumerable: true, get: function () { return correlation_middleware_1.CorrelationMiddleware; } });
Object.defineProperty(exports, "createCorrelationMiddleware", { enumerable: true, get: function () { return correlation_middleware_1.createCorrelationMiddleware; } });
var correlation_interceptor_1 = require("./interceptors/correlation.interceptor");
Object.defineProperty(exports, "CorrelationInterceptor", { enumerable: true, get: function () { return correlation_interceptor_1.CorrelationInterceptor; } });
Object.defineProperty(exports, "LoggingInterceptor", { enumerable: true, get: function () { return correlation_interceptor_1.LoggingInterceptor; } });
var correlation_id_decorator_1 = require("./decorators/correlation-id.decorator");
Object.defineProperty(exports, "CorrelationId", { enumerable: true, get: function () { return correlation_id_decorator_1.CorrelationId; } });
Object.defineProperty(exports, "CausationId", { enumerable: true, get: function () { return correlation_id_decorator_1.CausationId; } });
Object.defineProperty(exports, "CorrelationContextParam", { enumerable: true, get: function () { return correlation_id_decorator_1.CorrelationContextParam; } });
var tracer_1 = require("./otel/tracer");
Object.defineProperty(exports, "initializeTracer", { enumerable: true, get: function () { return tracer_1.initializeTracer; } });
Object.defineProperty(exports, "shutdownTracer", { enumerable: true, get: function () { return tracer_1.shutdownTracer; } });
Object.defineProperty(exports, "startSpan", { enumerable: true, get: function () { return tracer_1.startSpan; } });
Object.defineProperty(exports, "endSpan", { enumerable: true, get: function () { return tracer_1.endSpan; } });
Object.defineProperty(exports, "addSpanAttributes", { enumerable: true, get: function () { return tracer_1.addSpanAttributes; } });
Object.defineProperty(exports, "setSpanStatus", { enumerable: true, get: function () { return tracer_1.setSpanStatus; } });
Object.defineProperty(exports, "recordSpanError", { enumerable: true, get: function () { return tracer_1.recordSpanError; } });
Object.defineProperty(exports, "withSpan", { enumerable: true, get: function () { return tracer_1.withSpan; } });
Object.defineProperty(exports, "getActiveSpan", { enumerable: true, get: function () { return tracer_1.getActiveSpan; } });
Object.defineProperty(exports, "startChildSpan", { enumerable: true, get: function () { return tracer_1.startChildSpan; } });
Object.defineProperty(exports, "openTelemetryApi", { enumerable: true, get: function () { return tracer_1.openTelemetryApi; } });
var types_1 = require("./types");
Object.defineProperty(exports, "CORRELATION_ID_HEADER", { enumerable: true, get: function () { return types_1.CORRELATION_ID_HEADER; } });
Object.defineProperty(exports, "CAUSATION_ID_HEADER", { enumerable: true, get: function () { return types_1.CAUSATION_ID_HEADER; } });
Object.defineProperty(exports, "REQUEST_ID_HEADER", { enumerable: true, get: function () { return types_1.REQUEST_ID_HEADER; } });
//# sourceMappingURL=index.js.map