"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConsentStatus = exports.ConsentType = exports.ProcedureStatus = exports.TreatmentPhase = exports.ProcedureItemStatus = exports.TreatmentPlanStatus = exports.ClinicalNoteType = exports.FurcationClass = exports.ToothCondition = exports.ToothSurface = void 0;
var ToothSurface;
(function (ToothSurface) {
    ToothSurface["BUCCAL"] = "buccal";
    ToothSurface["FACIAL"] = "facial";
    ToothSurface["LINGUAL"] = "lingual";
    ToothSurface["PALATAL"] = "palatal";
    ToothSurface["MESIAL"] = "mesial";
    ToothSurface["DISTAL"] = "distal";
    ToothSurface["OCCLUSAL"] = "occlusal";
    ToothSurface["INCISAL"] = "incisal";
})(ToothSurface || (exports.ToothSurface = ToothSurface = {}));
var ToothCondition;
(function (ToothCondition) {
    ToothCondition["HEALTHY"] = "healthy";
    ToothCondition["CARIES"] = "caries";
    ToothCondition["RESTORED"] = "restored";
    ToothCondition["MISSING"] = "missing";
    ToothCondition["IMPACTED"] = "impacted";
    ToothCondition["UNERUPTED"] = "unerupted";
    ToothCondition["ECTOPIC"] = "ectopic";
    ToothCondition["CROWN"] = "crown";
    ToothCondition["BRIDGE"] = "bridge";
    ToothCondition["IMPLANT"] = "implant";
    ToothCondition["ROOT_CANAL"] = "root_canal";
    ToothCondition["FRACTURED"] = "fractured";
    ToothCondition["WORN"] = "worn";
    ToothCondition["WATCH"] = "watch";
    ToothCondition["EXTRACTION_NEEDED"] = "extraction_needed";
    ToothCondition["EXTRACTED"] = "extracted";
    ToothCondition["POST_AND_CORE"] = "post_and_core";
    ToothCondition["VENEER"] = "veneer";
    ToothCondition["ONLAY_INLAY"] = "onlay_inlay";
    ToothCondition["SEALANT"] = "sealant";
    ToothCondition["TEMPORARY"] = "temporary";
    ToothCondition["ROOT_REMNANTS"] = "root_remnants";
    ToothCondition["ABSCESS"] = "abscess";
    ToothCondition["MOBILE"] = "mobile";
    ToothCondition["DRIFTED"] = "drifted";
    ToothCondition["ROTATED"] = "rotated";
})(ToothCondition || (exports.ToothCondition = ToothCondition = {}));
var FurcationClass;
(function (FurcationClass) {
    FurcationClass["NONE"] = "none";
    FurcationClass["CLASS_I"] = "class_1";
    FurcationClass["CLASS_II"] = "class_2";
    FurcationClass["CLASS_III"] = "class_3";
    FurcationClass["CLASS_IV"] = "class_4";
})(FurcationClass || (exports.FurcationClass = FurcationClass = {}));
var ClinicalNoteType;
(function (ClinicalNoteType) {
    ClinicalNoteType["SOAP"] = "soap";
    ClinicalNoteType["PROGRESS"] = "progress";
    ClinicalNoteType["CONSULT"] = "consult";
    ClinicalNoteType["EMERGENCY"] = "emergency";
    ClinicalNoteType["OPERATIVE"] = "operative";
    ClinicalNoteType["PHONE"] = "phone";
    ClinicalNoteType["FOLLOWUP"] = "followup";
    ClinicalNoteType["INITIAL_EVAL"] = "initial_eval";
    ClinicalNoteType["REFERRAL"] = "referral";
})(ClinicalNoteType || (exports.ClinicalNoteType = ClinicalNoteType = {}));
var TreatmentPlanStatus;
(function (TreatmentPlanStatus) {
    TreatmentPlanStatus["DRAFT"] = "draft";
    TreatmentPlanStatus["PENDING"] = "pending";
    TreatmentPlanStatus["APPROVED"] = "approved";
    TreatmentPlanStatus["IN_PROGRESS"] = "in_progress";
    TreatmentPlanStatus["COMPLETED"] = "completed";
    TreatmentPlanStatus["CANCELLED"] = "cancelled";
    TreatmentPlanStatus["EXPIRED"] = "expired";
    TreatmentPlanStatus["ON_HOLD"] = "on_hold";
})(TreatmentPlanStatus || (exports.TreatmentPlanStatus = TreatmentPlanStatus = {}));
var ProcedureItemStatus;
(function (ProcedureItemStatus) {
    ProcedureItemStatus["PLANNED"] = "planned";
    ProcedureItemStatus["SCHEDULED"] = "scheduled";
    ProcedureItemStatus["IN_PROGRESS"] = "in_progress";
    ProcedureItemStatus["COMPLETED"] = "completed";
    ProcedureItemStatus["CANCELLED"] = "cancelled";
    ProcedureItemStatus["ON_HOLD"] = "on_hold";
})(ProcedureItemStatus || (exports.ProcedureItemStatus = ProcedureItemStatus = {}));
var TreatmentPhase;
(function (TreatmentPhase) {
    TreatmentPhase["EMERGENCY"] = "emergency";
    TreatmentPhase["STABILIZATION"] = "stabilization";
    TreatmentPhase["RESTORATIVE"] = "restorative";
    TreatmentPhase["PERIODONTAL"] = "periodontal";
    TreatmentPhase["ENDODONTIC"] = "endodontic";
    TreatmentPhase["SURGICAL"] = "surgical";
    TreatmentPhase["ORTHODONTIC"] = "orthodontic";
    TreatmentPhase["PROSTHETIC"] = "prosthetic";
    TreatmentPhase["COSMETIC"] = "cosmetic";
    TreatmentPhase["MAINTENANCE"] = "maintenance";
})(TreatmentPhase || (exports.TreatmentPhase = TreatmentPhase = {}));
var ProcedureStatus;
(function (ProcedureStatus) {
    ProcedureStatus["SCHEDULED"] = "scheduled";
    ProcedureStatus["IN_PROGRESS"] = "in_progress";
    ProcedureStatus["COMPLETED"] = "completed";
    ProcedureStatus["PARTIALLY_COMPLETED"] = "partially_completed";
    ProcedureStatus["CANCELLED"] = "cancelled";
    ProcedureStatus["FAILED"] = "failed";
})(ProcedureStatus || (exports.ProcedureStatus = ProcedureStatus = {}));
var ConsentType;
(function (ConsentType) {
    ConsentType["TREATMENT"] = "treatment";
    ConsentType["ANESTHESIA"] = "anesthesia";
    ConsentType["SEDATION"] = "sedation";
    ConsentType["SURGICAL"] = "surgical";
    ConsentType["FINANCIAL"] = "financial";
    ConsentType["HIPAA"] = "hipaa";
    ConsentType["PHOTOGRAPHY"] = "photography";
    ConsentType["RESEARCH"] = "research";
    ConsentType["MINOR"] = "minor";
    ConsentType["RECORDS_RELEASE"] = "records_release";
    ConsentType["REFERRAL"] = "referral";
    ConsentType["TELEDENTISTRY"] = "teledentistry";
    ConsentType["GDPR"] = "gdpr";
})(ConsentType || (exports.ConsentType = ConsentType = {}));
var ConsentStatus;
(function (ConsentStatus) {
    ConsentStatus["PENDING"] = "pending";
    ConsentStatus["SIGNED"] = "signed";
    ConsentStatus["DECLINED"] = "declined";
    ConsentStatus["EXPIRED"] = "expired";
    ConsentStatus["REVOKED"] = "revoked";
    ConsentStatus["VOIDED"] = "voided";
})(ConsentStatus || (exports.ConsentStatus = ConsentStatus = {}));
//# sourceMappingURL=clinical.types.js.map