"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createPatientAnonymizedEvent = exports.isPatientAnonymizedEvent = exports.PATIENT_ANONYMIZED_EVENT_VERSION = exports.PATIENT_ANONYMIZED_EVENT = exports.createPatientDeletedEvent = exports.isPatientDeletedEvent = exports.PATIENT_DELETED_EVENT_VERSION = exports.PATIENT_DELETED_EVENT = exports.createPatientMergedEvent = exports.isPatientMergedEvent = exports.PATIENT_MERGED_EVENT_VERSION = exports.PATIENT_MERGED_EVENT = exports.createPatientUpdatedEvent = exports.isPatientUpdatedEvent = exports.PATIENT_UPDATED_EVENT_VERSION = exports.PATIENT_UPDATED_EVENT = exports.createPatientCreatedEvent = exports.isPatientCreatedEvent = exports.PATIENT_CREATED_EVENT_VERSION = exports.PATIENT_CREATED_EVENT = void 0;
var patient_created_event_1 = require("./patient-created.event");
Object.defineProperty(exports, "PATIENT_CREATED_EVENT", { enumerable: true, get: function () { return patient_created_event_1.PATIENT_CREATED_EVENT; } });
Object.defineProperty(exports, "PATIENT_CREATED_EVENT_VERSION", { enumerable: true, get: function () { return patient_created_event_1.PATIENT_CREATED_EVENT_VERSION; } });
Object.defineProperty(exports, "isPatientCreatedEvent", { enumerable: true, get: function () { return patient_created_event_1.isPatientCreatedEvent; } });
Object.defineProperty(exports, "createPatientCreatedEvent", { enumerable: true, get: function () { return patient_created_event_1.createPatientCreatedEvent; } });
var patient_updated_event_1 = require("./patient-updated.event");
Object.defineProperty(exports, "PATIENT_UPDATED_EVENT", { enumerable: true, get: function () { return patient_updated_event_1.PATIENT_UPDATED_EVENT; } });
Object.defineProperty(exports, "PATIENT_UPDATED_EVENT_VERSION", { enumerable: true, get: function () { return patient_updated_event_1.PATIENT_UPDATED_EVENT_VERSION; } });
Object.defineProperty(exports, "isPatientUpdatedEvent", { enumerable: true, get: function () { return patient_updated_event_1.isPatientUpdatedEvent; } });
Object.defineProperty(exports, "createPatientUpdatedEvent", { enumerable: true, get: function () { return patient_updated_event_1.createPatientUpdatedEvent; } });
var patient_merged_event_1 = require("./patient-merged.event");
Object.defineProperty(exports, "PATIENT_MERGED_EVENT", { enumerable: true, get: function () { return patient_merged_event_1.PATIENT_MERGED_EVENT; } });
Object.defineProperty(exports, "PATIENT_MERGED_EVENT_VERSION", { enumerable: true, get: function () { return patient_merged_event_1.PATIENT_MERGED_EVENT_VERSION; } });
Object.defineProperty(exports, "isPatientMergedEvent", { enumerable: true, get: function () { return patient_merged_event_1.isPatientMergedEvent; } });
Object.defineProperty(exports, "createPatientMergedEvent", { enumerable: true, get: function () { return patient_merged_event_1.createPatientMergedEvent; } });
var patient_deleted_event_1 = require("./patient-deleted.event");
Object.defineProperty(exports, "PATIENT_DELETED_EVENT", { enumerable: true, get: function () { return patient_deleted_event_1.PATIENT_DELETED_EVENT; } });
Object.defineProperty(exports, "PATIENT_DELETED_EVENT_VERSION", { enumerable: true, get: function () { return patient_deleted_event_1.PATIENT_DELETED_EVENT_VERSION; } });
Object.defineProperty(exports, "isPatientDeletedEvent", { enumerable: true, get: function () { return patient_deleted_event_1.isPatientDeletedEvent; } });
Object.defineProperty(exports, "createPatientDeletedEvent", { enumerable: true, get: function () { return patient_deleted_event_1.createPatientDeletedEvent; } });
var patient_anonymized_event_1 = require("./patient-anonymized.event");
Object.defineProperty(exports, "PATIENT_ANONYMIZED_EVENT", { enumerable: true, get: function () { return patient_anonymized_event_1.PATIENT_ANONYMIZED_EVENT; } });
Object.defineProperty(exports, "PATIENT_ANONYMIZED_EVENT_VERSION", { enumerable: true, get: function () { return patient_anonymized_event_1.PATIENT_ANONYMIZED_EVENT_VERSION; } });
Object.defineProperty(exports, "isPatientAnonymizedEvent", { enumerable: true, get: function () { return patient_anonymized_event_1.isPatientAnonymizedEvent; } });
Object.defineProperty(exports, "createPatientAnonymizedEvent", { enumerable: true, get: function () { return patient_anonymized_event_1.createPatientAnonymizedEvent; } });
//# sourceMappingURL=index.js.map