"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.shouldLogError = exports.calculateRetryDelay = exports.isTransientError = exports.isOperationalError = exports.extractCorrelationId = exports.extractErrorCode = exports.isCriticalError = exports.isUserError = exports.isRetryableError = exports.extractErrorCodeFromBuilder = exports.buildProductionErrorResponse = exports.buildDevelopmentErrorResponse = exports.sanitizeMetadata = exports.sanitizeErrorForClient = exports.buildErrorResponse = exports.getStatusDescription = exports.isServerError = exports.isClientError = exports.mapErrorCodeToHttpStatus = exports.mapErrorToHttpStatus = exports.TenantIsolationError = exports.RateLimitError = exports.InfrastructureError = exports.SecurityError = exports.AuthorizationError = exports.AuthenticationError = exports.DomainError = exports.ConflictError = exports.NotFoundError = exports.ValidationError = exports.BaseError = void 0;
var base_1 = require("./base");
Object.defineProperty(exports, "BaseError", { enumerable: true, get: function () { return base_1.BaseError; } });
var domain_1 = require("./domain");
Object.defineProperty(exports, "ValidationError", { enumerable: true, get: function () { return domain_1.ValidationError; } });
var domain_2 = require("./domain");
Object.defineProperty(exports, "NotFoundError", { enumerable: true, get: function () { return domain_2.NotFoundError; } });
var domain_3 = require("./domain");
Object.defineProperty(exports, "ConflictError", { enumerable: true, get: function () { return domain_3.ConflictError; } });
var domain_4 = require("./domain");
Object.defineProperty(exports, "DomainError", { enumerable: true, get: function () { return domain_4.DomainError; } });
var auth_1 = require("./auth");
Object.defineProperty(exports, "AuthenticationError", { enumerable: true, get: function () { return auth_1.AuthenticationError; } });
var auth_2 = require("./auth");
Object.defineProperty(exports, "AuthorizationError", { enumerable: true, get: function () { return auth_2.AuthorizationError; } });
var auth_3 = require("./auth");
Object.defineProperty(exports, "SecurityError", { enumerable: true, get: function () { return auth_3.SecurityError; } });
var infra_1 = require("./infra");
Object.defineProperty(exports, "InfrastructureError", { enumerable: true, get: function () { return infra_1.InfrastructureError; } });
var infra_2 = require("./infra");
Object.defineProperty(exports, "RateLimitError", { enumerable: true, get: function () { return infra_2.RateLimitError; } });
var tenant_1 = require("./tenant");
Object.defineProperty(exports, "TenantIsolationError", { enumerable: true, get: function () { return tenant_1.TenantIsolationError; } });
var mappers_1 = require("./mappers");
Object.defineProperty(exports, "mapErrorToHttpStatus", { enumerable: true, get: function () { return mappers_1.mapErrorToHttpStatus; } });
Object.defineProperty(exports, "mapErrorCodeToHttpStatus", { enumerable: true, get: function () { return mappers_1.mapErrorCodeToHttpStatus; } });
Object.defineProperty(exports, "isClientError", { enumerable: true, get: function () { return mappers_1.isClientError; } });
Object.defineProperty(exports, "isServerError", { enumerable: true, get: function () { return mappers_1.isServerError; } });
Object.defineProperty(exports, "getStatusDescription", { enumerable: true, get: function () { return mappers_1.getStatusDescription; } });
var mappers_2 = require("./mappers");
Object.defineProperty(exports, "buildErrorResponse", { enumerable: true, get: function () { return mappers_2.buildErrorResponse; } });
Object.defineProperty(exports, "sanitizeErrorForClient", { enumerable: true, get: function () { return mappers_2.sanitizeErrorForClient; } });
Object.defineProperty(exports, "sanitizeMetadata", { enumerable: true, get: function () { return mappers_2.sanitizeMetadata; } });
Object.defineProperty(exports, "buildDevelopmentErrorResponse", { enumerable: true, get: function () { return mappers_2.buildDevelopmentErrorResponse; } });
Object.defineProperty(exports, "buildProductionErrorResponse", { enumerable: true, get: function () { return mappers_2.buildProductionErrorResponse; } });
Object.defineProperty(exports, "extractErrorCodeFromBuilder", { enumerable: true, get: function () { return mappers_2.extractErrorCode; } });
var utils_1 = require("./utils");
Object.defineProperty(exports, "isRetryableError", { enumerable: true, get: function () { return utils_1.isRetryableError; } });
Object.defineProperty(exports, "isUserError", { enumerable: true, get: function () { return utils_1.isUserError; } });
Object.defineProperty(exports, "isCriticalError", { enumerable: true, get: function () { return utils_1.isCriticalError; } });
Object.defineProperty(exports, "extractErrorCode", { enumerable: true, get: function () { return utils_1.extractErrorCode; } });
Object.defineProperty(exports, "extractCorrelationId", { enumerable: true, get: function () { return utils_1.extractCorrelationId; } });
Object.defineProperty(exports, "isOperationalError", { enumerable: true, get: function () { return utils_1.isOperationalError; } });
Object.defineProperty(exports, "isTransientError", { enumerable: true, get: function () { return utils_1.isTransientError; } });
Object.defineProperty(exports, "calculateRetryDelay", { enumerable: true, get: function () { return utils_1.calculateRetryDelay; } });
Object.defineProperty(exports, "shouldLogError", { enumerable: true, get: function () { return utils_1.shouldLogError; } });
//# sourceMappingURL=index.js.map