"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClinicFilterDtoSchema = exports.OrganizationFilterDtoSchema = exports.AssignProviderDtoSchema = exports.WorkingHoursOverrideSchema = exports.CreateClinicLocationDtoSchema = exports.UpdateClinicSettingsDtoSchema = exports.EnterpriseUpdateClinicDtoSchema = exports.EnterpriseCreateClinicDtoSchema = exports.OperatingHoursSchema = exports.AddOrganizationAdminDtoSchema = exports.UpdateOrganizationSettingsDtoSchema = exports.EnterpriseUpdateOrganizationDtoSchema = exports.EnterpriseCreateOrganizationDtoSchema = exports.EnterpriseAddressSchema = void 0;
const zod_1 = require("zod");
const shared_domain_1 = require("@dentalos/shared-domain");
const common_schemas_1 = require("../common.schemas");
exports.EnterpriseAddressSchema = zod_1.z.object({
    street: common_schemas_1.NonEmptyStringSchema.max(200),
    city: common_schemas_1.NonEmptyStringSchema.max(100),
    state: common_schemas_1.NonEmptyStringSchema.max(100),
    postalCode: common_schemas_1.NonEmptyStringSchema.max(20),
    country: common_schemas_1.NonEmptyStringSchema.max(100),
});
exports.EnterpriseCreateOrganizationDtoSchema = zod_1.z.object({
    name: common_schemas_1.NonEmptyStringSchema.max(200),
    legalName: common_schemas_1.NonEmptyStringSchema.max(200),
    taxId: common_schemas_1.NonEmptyStringSchema.max(50),
    primaryContactName: common_schemas_1.NonEmptyStringSchema.max(200),
    primaryContactEmail: zod_1.z.string().email(),
    primaryContactPhone: common_schemas_1.NonEmptyStringSchema.max(50),
    address: exports.EnterpriseAddressSchema,
    website: zod_1.z.string().url().optional(),
    logoUrl: zod_1.z.string().url().optional(),
    subscriptionTier: zod_1.z.enum(['FREE', 'BASIC', 'PRO', 'ENTERPRISE']),
    subscriptionStartDate: common_schemas_1.ISODateStringSchema,
    subscriptionEndDate: common_schemas_1.ISODateStringSchema.optional(),
    maxClinics: zod_1.z.number().int().positive(),
    maxUsers: zod_1.z.number().int().positive(),
    maxStorageGB: zod_1.z.number().positive(),
});
exports.EnterpriseUpdateOrganizationDtoSchema = zod_1.z.object({
    name: common_schemas_1.NonEmptyStringSchema.max(200).optional(),
    legalName: common_schemas_1.NonEmptyStringSchema.max(200).optional(),
    taxId: common_schemas_1.NonEmptyStringSchema.max(50).optional(),
    status: zod_1.z.nativeEnum(shared_domain_1.OrganizationStatus).optional(),
    primaryContactName: common_schemas_1.NonEmptyStringSchema.max(200).optional(),
    primaryContactEmail: zod_1.z.string().email().optional(),
    primaryContactPhone: common_schemas_1.NonEmptyStringSchema.max(50).optional(),
    address: exports.EnterpriseAddressSchema.optional(),
    website: zod_1.z.string().url().optional(),
    logoUrl: zod_1.z.string().url().optional(),
    subscriptionTier: zod_1.z.enum(['FREE', 'BASIC', 'PRO', 'ENTERPRISE']).optional(),
    subscriptionEndDate: common_schemas_1.ISODateStringSchema.optional(),
    maxClinics: zod_1.z.number().int().positive().optional(),
    maxUsers: zod_1.z.number().int().positive().optional(),
    maxStorageGB: zod_1.z.number().positive().optional(),
});
exports.UpdateOrganizationSettingsDtoSchema = zod_1.z.object({
    brandPrimaryColor: zod_1.z.string().regex(/^#[0-9A-Fa-f]{6}$/).optional(),
    brandSecondaryColor: zod_1.z.string().regex(/^#[0-9A-Fa-f]{6}$/).optional(),
    customDomain: zod_1.z.string().optional(),
    enableMultiClinic: zod_1.z.boolean().optional(),
    enableAdvancedAnalytics: zod_1.z.boolean().optional(),
    enableAIPredictions: zod_1.z.boolean().optional(),
    enableMarketingAutomation: zod_1.z.boolean().optional(),
    enableInventoryManagement: zod_1.z.boolean().optional(),
    enableSterilizationTracking: zod_1.z.boolean().optional(),
    enableLabIntegration: zod_1.z.boolean().optional(),
    requireMFA: zod_1.z.boolean().optional(),
    passwordMinLength: zod_1.z.number().int().min(8).max(128).optional(),
    sessionTimeoutMinutes: zod_1.z.number().int().positive().optional(),
    allowedIPRanges: zod_1.z.array(zod_1.z.string()).optional(),
    enableHIPAAMode: zod_1.z.boolean().optional(),
    enableGDPRMode: zod_1.z.boolean().optional(),
    dataRetentionDays: zod_1.z.number().int().positive().optional(),
    requireConsentForMarketing: zod_1.z.boolean().optional(),
    defaultTimezone: zod_1.z.string().optional(),
    defaultLanguage: zod_1.z.string().optional(),
    notificationEmail: zod_1.z.string().email().optional(),
});
exports.AddOrganizationAdminDtoSchema = zod_1.z.object({
    userId: common_schemas_1.UUIDSchema,
    email: zod_1.z.string().email(),
    fullName: common_schemas_1.NonEmptyStringSchema.max(200),
    role: zod_1.z.nativeEnum(shared_domain_1.EnterpriseRole),
});
exports.OperatingHoursSchema = zod_1.z.object({
    monday: zod_1.z.object({ open: zod_1.z.string(), close: zod_1.z.string() }).optional(),
    tuesday: zod_1.z.object({ open: zod_1.z.string(), close: zod_1.z.string() }).optional(),
    wednesday: zod_1.z.object({ open: zod_1.z.string(), close: zod_1.z.string() }).optional(),
    thursday: zod_1.z.object({ open: zod_1.z.string(), close: zod_1.z.string() }).optional(),
    friday: zod_1.z.object({ open: zod_1.z.string(), close: zod_1.z.string() }).optional(),
    saturday: zod_1.z.object({ open: zod_1.z.string(), close: zod_1.z.string() }).optional(),
    sunday: zod_1.z.object({ open: zod_1.z.string(), close: zod_1.z.string() }).optional(),
}).optional();
exports.EnterpriseCreateClinicDtoSchema = zod_1.z.object({
    name: common_schemas_1.NonEmptyStringSchema.max(200),
    code: common_schemas_1.NonEmptyStringSchema.max(50),
    address: exports.EnterpriseAddressSchema,
    phone: common_schemas_1.NonEmptyStringSchema.max(50),
    email: zod_1.z.string().email(),
    website: zod_1.z.string().url().optional(),
    managerUserId: common_schemas_1.UUIDSchema.optional(),
    managerName: common_schemas_1.NonEmptyStringSchema.max(200).optional(),
    managerEmail: zod_1.z.string().email().optional(),
    timezone: zod_1.z.string(),
    locale: zod_1.z.string().default('en-US'),
    operatingHours: exports.OperatingHoursSchema,
    licenseNumber: zod_1.z.string().optional(),
    accreditationDetails: zod_1.z.string().optional(),
});
exports.EnterpriseUpdateClinicDtoSchema = zod_1.z.object({
    name: common_schemas_1.NonEmptyStringSchema.max(200).optional(),
    code: common_schemas_1.NonEmptyStringSchema.max(50).optional(),
    status: zod_1.z.nativeEnum(shared_domain_1.ClinicStatus).optional(),
    address: exports.EnterpriseAddressSchema.optional(),
    phone: common_schemas_1.NonEmptyStringSchema.max(50).optional(),
    email: zod_1.z.string().email().optional(),
    website: zod_1.z.string().url().optional(),
    managerUserId: common_schemas_1.UUIDSchema.optional(),
    managerName: common_schemas_1.NonEmptyStringSchema.max(200).optional(),
    managerEmail: zod_1.z.string().email().optional(),
    timezone: zod_1.z.string().optional(),
    locale: zod_1.z.string().optional(),
    operatingHours: exports.OperatingHoursSchema,
    licenseNumber: zod_1.z.string().optional(),
    accreditationDetails: zod_1.z.string().optional(),
});
exports.UpdateClinicSettingsDtoSchema = zod_1.z.object({
    defaultAppointmentDurationMinutes: zod_1.z.number().int().positive().optional(),
    allowOnlineBooking: zod_1.z.boolean().optional(),
    requireDepositForBooking: zod_1.z.boolean().optional(),
    depositPercentage: zod_1.z.number().min(0).max(100).optional(),
    cancellationPolicyHours: zod_1.z.number().int().nonnegative().optional(),
    defaultCurrency: zod_1.z.string().length(3).optional(),
    acceptedPaymentMethods: zod_1.z.array(zod_1.z.string()).optional(),
    invoicePrefix: zod_1.z.string().max(10).optional(),
    taxRate: zod_1.z.number().min(0).max(100).optional(),
    sendAutomaticReminders: zod_1.z.boolean().optional(),
    useElectronicRecords: zod_1.z.boolean().optional(),
    requireConsentForTreatment: zod_1.z.boolean().optional(),
    defaultConsentFormIds: zod_1.z.array(common_schemas_1.UUIDSchema).optional(),
    enableInventoryTracking: zod_1.z.boolean().optional(),
    lowStockThreshold: zod_1.z.number().int().positive().optional(),
    autoReorderEnabled: zod_1.z.boolean().optional(),
    enableSterilizationTracking: zod_1.z.boolean().optional(),
    requireBiologicalIndicators: zod_1.z.boolean().optional(),
    sterilizationCyclePrefix: zod_1.z.string().max(10).optional(),
    enableLoyaltyProgram: zod_1.z.boolean().optional(),
    loyaltyPointsPerDollar: zod_1.z.number().nonnegative().optional(),
    enableReferralRewards: zod_1.z.boolean().optional(),
    sendAppointmentReminders: zod_1.z.boolean().optional(),
    reminderHoursBefore: zod_1.z.array(zod_1.z.number().int().positive()).optional(),
    sendPostTreatmentFollowup: zod_1.z.boolean().optional(),
    followupDaysAfter: zod_1.z.number().int().positive().optional(),
});
exports.CreateClinicLocationDtoSchema = zod_1.z.object({
    type: zod_1.z.nativeEnum(shared_domain_1.ClinicLocationType),
    name: common_schemas_1.NonEmptyStringSchema.max(200),
    code: common_schemas_1.NonEmptyStringSchema.max(50),
    parentLocationId: common_schemas_1.UUIDSchema.optional(),
    floor: zod_1.z.number().int().optional(),
    area: zod_1.z.string().max(100).optional(),
    capacity: zod_1.z.number().int().positive().optional(),
    notes: zod_1.z.string().optional(),
    equipmentIds: zod_1.z.array(common_schemas_1.UUIDSchema).optional(),
    assignedStaffIds: zod_1.z.array(common_schemas_1.UUIDSchema).optional(),
});
exports.WorkingHoursOverrideSchema = zod_1.z.object({
    monday: zod_1.z.object({ start: zod_1.z.string(), end: zod_1.z.string() }).optional(),
    tuesday: zod_1.z.object({ start: zod_1.z.string(), end: zod_1.z.string() }).optional(),
    wednesday: zod_1.z.object({ start: zod_1.z.string(), end: zod_1.z.string() }).optional(),
    thursday: zod_1.z.object({ start: zod_1.z.string(), end: zod_1.z.string() }).optional(),
    friday: zod_1.z.object({ start: zod_1.z.string(), end: zod_1.z.string() }).optional(),
    saturday: zod_1.z.object({ start: zod_1.z.string(), end: zod_1.z.string() }).optional(),
    sunday: zod_1.z.object({ start: zod_1.z.string(), end: zod_1.z.string() }).optional(),
}).optional();
exports.AssignProviderDtoSchema = zod_1.z.object({
    clinicId: common_schemas_1.UUIDSchema,
    roles: zod_1.z.array(zod_1.z.string()).min(1),
    isPrimaryClinic: zod_1.z.boolean().default(false),
    workingHoursOverride: exports.WorkingHoursOverrideSchema,
});
exports.OrganizationFilterDtoSchema = zod_1.z.object({
    status: zod_1.z.nativeEnum(shared_domain_1.OrganizationStatus).optional(),
    subscriptionTier: zod_1.z.enum(['FREE', 'BASIC', 'PRO', 'ENTERPRISE']).optional(),
    limit: zod_1.z.number().int().positive().max(100).default(20),
    offset: zod_1.z.number().int().nonnegative().default(0),
});
exports.ClinicFilterDtoSchema = zod_1.z.object({
    organizationId: common_schemas_1.UUIDSchema.optional(),
    status: zod_1.z.nativeEnum(shared_domain_1.ClinicStatus).optional(),
    limit: zod_1.z.number().int().positive().max(100).default(20),
    offset: zod_1.z.number().int().nonnegative().default(0),
});
//# sourceMappingURL=enterprise.schemas.js.map