"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MODULE_METADATA_KEY = exports.getModuleMetadata = exports.RequiresModule = exports.ROLE_METADATA_KEY = exports.getRoleMetadata = exports.RequireAllRoles = exports.RequireRoles = exports.PERMISSION_METADATA_KEY = exports.getPermissionMetadata = exports.RequireAnyPermission = exports.RequirePermissions = exports.toScope = exports.hasAnyScope = exports.hasAllScopes = exports.hasScopeForResource = exports.hasScope = exports.extractScopes = exports.hasFullAccess = exports.getResourcePermissions = exports.canAccessResource = exports.hasAnyPermission = exports.hasAllPermissions = exports.hasPermission = exports.isClinicalStaff = exports.isClinicAdmin = exports.isOrgAdmin = exports.isSuperAdmin = exports.hasAllRoles = exports.hasAnyRole = exports.hasRole = exports.getSessionTimeRemaining = exports.isSessionExpired = exports.createSession = exports.isClinicLevel = exports.isOrganizationLevel = exports.createTenantContext = exports.extractTenantContext = exports.createCurrentUser = exports.SubscriptionStatus = exports.ModuleCode = exports.getTokenAge = exports.willExpireWithin = exports.getTimeUntilExpiration = exports.getTokenExpiration = exports.isTokenExpired = exports.JWTVerificationError = exports.JWTError = exports.extractPayload = exports.verifyRefreshToken = exports.verifyAccessToken = void 0;
exports.canAccessModule = exports.getPremiumModules = exports.getCoreModules = exports.hasOnlyCoreModules = exports.hasPremiumAccess = exports.isInGracePeriodSimple = exports.isSubscriptionActive = exports.getAvailableModules = exports.hasAllModules = exports.hasAnyModule = exports.hasModule = exports.dependsOn = exports.validateModuleDependencies = exports.getDependencyErrorMessage = exports.areDependenciesSatisfied = exports.getAllMissingDependencies = exports.getMissingDependencies = exports.hasModuleDependencies = exports.getAllModuleDependencies = exports.getModuleDependencies = exports.getGracePeriodStatusMessage = exports.calculateGracePeriodEnd = exports.canPerformWriteOperation = exports.canPerformOperation = exports.isWriteOperation = exports.isReadOperation = exports.isGracePeriodExpiringSoon = exports.getGracePeriodDaysRemaining = exports.isInGracePeriod = exports.ALL_MODULES = exports.PREMIUM_MODULES = exports.CORE_MODULES = exports.WRITE_METHODS = exports.READ_METHODS = exports.GRACE_PERIOD_DAYS = exports.TenantIsolationError = exports.validateClinicAccess = exports.validateOrganizationAccess = exports.ensureTenantIsolation = exports.validateTenantAccess = exports.hasClinicLevelAccess = exports.hasOrganizationLevelAccess = exports.canAccessClinic = exports.canAccessOrganization = exports.belongsToClinic = exports.belongsToOrganization = exports.isSameTenant = exports.ALLOW_GRACE_PERIOD_KEY = exports.SubscriptionStatusGuard = exports.LicenseGuard = void 0;
exports.LicenseForbiddenException = exports.LicenseValidatorService = exports.getSubscriptionStatus = exports.isSubscriptionExpired = exports.isTrialUser = exports.getMissingModules = void 0;
var jwt_1 = require("./jwt");
Object.defineProperty(exports, "verifyAccessToken", { enumerable: true, get: function () { return jwt_1.verifyAccessToken; } });
Object.defineProperty(exports, "verifyRefreshToken", { enumerable: true, get: function () { return jwt_1.verifyRefreshToken; } });
Object.defineProperty(exports, "extractPayload", { enumerable: true, get: function () { return jwt_1.extractPayload; } });
Object.defineProperty(exports, "JWTError", { enumerable: true, get: function () { return jwt_1.JWTError; } });
Object.defineProperty(exports, "JWTVerificationError", { enumerable: true, get: function () { return jwt_1.JWTVerificationError; } });
Object.defineProperty(exports, "isTokenExpired", { enumerable: true, get: function () { return jwt_1.isTokenExpired; } });
Object.defineProperty(exports, "getTokenExpiration", { enumerable: true, get: function () { return jwt_1.getTokenExpiration; } });
Object.defineProperty(exports, "getTimeUntilExpiration", { enumerable: true, get: function () { return jwt_1.getTimeUntilExpiration; } });
Object.defineProperty(exports, "willExpireWithin", { enumerable: true, get: function () { return jwt_1.willExpireWithin; } });
Object.defineProperty(exports, "getTokenAge", { enumerable: true, get: function () { return jwt_1.getTokenAge; } });
Object.defineProperty(exports, "ModuleCode", { enumerable: true, get: function () { return jwt_1.ModuleCode; } });
Object.defineProperty(exports, "SubscriptionStatus", { enumerable: true, get: function () { return jwt_1.SubscriptionStatus; } });
var context_1 = require("./context");
Object.defineProperty(exports, "createCurrentUser", { enumerable: true, get: function () { return context_1.createCurrentUser; } });
Object.defineProperty(exports, "extractTenantContext", { enumerable: true, get: function () { return context_1.extractTenantContext; } });
Object.defineProperty(exports, "createTenantContext", { enumerable: true, get: function () { return context_1.createTenantContext; } });
Object.defineProperty(exports, "isOrganizationLevel", { enumerable: true, get: function () { return context_1.isOrganizationLevel; } });
Object.defineProperty(exports, "isClinicLevel", { enumerable: true, get: function () { return context_1.isClinicLevel; } });
Object.defineProperty(exports, "createSession", { enumerable: true, get: function () { return context_1.createSession; } });
Object.defineProperty(exports, "isSessionExpired", { enumerable: true, get: function () { return context_1.isSessionExpired; } });
Object.defineProperty(exports, "getSessionTimeRemaining", { enumerable: true, get: function () { return context_1.getSessionTimeRemaining; } });
var rbac_1 = require("./rbac");
Object.defineProperty(exports, "hasRole", { enumerable: true, get: function () { return rbac_1.hasRole; } });
Object.defineProperty(exports, "hasAnyRole", { enumerable: true, get: function () { return rbac_1.hasAnyRole; } });
Object.defineProperty(exports, "hasAllRoles", { enumerable: true, get: function () { return rbac_1.hasAllRoles; } });
Object.defineProperty(exports, "isSuperAdmin", { enumerable: true, get: function () { return rbac_1.isSuperAdmin; } });
Object.defineProperty(exports, "isOrgAdmin", { enumerable: true, get: function () { return rbac_1.isOrgAdmin; } });
Object.defineProperty(exports, "isClinicAdmin", { enumerable: true, get: function () { return rbac_1.isClinicAdmin; } });
Object.defineProperty(exports, "isClinicalStaff", { enumerable: true, get: function () { return rbac_1.isClinicalStaff; } });
Object.defineProperty(exports, "hasPermission", { enumerable: true, get: function () { return rbac_1.hasPermission; } });
Object.defineProperty(exports, "hasAllPermissions", { enumerable: true, get: function () { return rbac_1.hasAllPermissions; } });
Object.defineProperty(exports, "hasAnyPermission", { enumerable: true, get: function () { return rbac_1.hasAnyPermission; } });
Object.defineProperty(exports, "canAccessResource", { enumerable: true, get: function () { return rbac_1.canAccessResource; } });
Object.defineProperty(exports, "getResourcePermissions", { enumerable: true, get: function () { return rbac_1.getResourcePermissions; } });
Object.defineProperty(exports, "hasFullAccess", { enumerable: true, get: function () { return rbac_1.hasFullAccess; } });
Object.defineProperty(exports, "extractScopes", { enumerable: true, get: function () { return rbac_1.extractScopes; } });
Object.defineProperty(exports, "hasScope", { enumerable: true, get: function () { return rbac_1.hasScope; } });
Object.defineProperty(exports, "hasScopeForResource", { enumerable: true, get: function () { return rbac_1.hasScopeForResource; } });
Object.defineProperty(exports, "hasAllScopes", { enumerable: true, get: function () { return rbac_1.hasAllScopes; } });
Object.defineProperty(exports, "hasAnyScope", { enumerable: true, get: function () { return rbac_1.hasAnyScope; } });
Object.defineProperty(exports, "toScope", { enumerable: true, get: function () { return rbac_1.toScope; } });
var guards_1 = require("./guards");
Object.defineProperty(exports, "RequirePermissions", { enumerable: true, get: function () { return guards_1.RequirePermissions; } });
Object.defineProperty(exports, "RequireAnyPermission", { enumerable: true, get: function () { return guards_1.RequireAnyPermission; } });
Object.defineProperty(exports, "getPermissionMetadata", { enumerable: true, get: function () { return guards_1.getPermissionMetadata; } });
Object.defineProperty(exports, "PERMISSION_METADATA_KEY", { enumerable: true, get: function () { return guards_1.PERMISSION_METADATA_KEY; } });
Object.defineProperty(exports, "RequireRoles", { enumerable: true, get: function () { return guards_1.RequireRoles; } });
Object.defineProperty(exports, "RequireAllRoles", { enumerable: true, get: function () { return guards_1.RequireAllRoles; } });
Object.defineProperty(exports, "getRoleMetadata", { enumerable: true, get: function () { return guards_1.getRoleMetadata; } });
Object.defineProperty(exports, "ROLE_METADATA_KEY", { enumerable: true, get: function () { return guards_1.ROLE_METADATA_KEY; } });
Object.defineProperty(exports, "RequiresModule", { enumerable: true, get: function () { return guards_1.RequiresModule; } });
Object.defineProperty(exports, "getModuleMetadata", { enumerable: true, get: function () { return guards_1.getModuleMetadata; } });
Object.defineProperty(exports, "MODULE_METADATA_KEY", { enumerable: true, get: function () { return guards_1.MODULE_METADATA_KEY; } });
Object.defineProperty(exports, "LicenseGuard", { enumerable: true, get: function () { return guards_1.LicenseGuard; } });
Object.defineProperty(exports, "SubscriptionStatusGuard", { enumerable: true, get: function () { return guards_1.SubscriptionStatusGuard; } });
Object.defineProperty(exports, "ALLOW_GRACE_PERIOD_KEY", { enumerable: true, get: function () { return guards_1.ALLOW_GRACE_PERIOD_KEY; } });
var multi_tenant_1 = require("./multi-tenant");
Object.defineProperty(exports, "isSameTenant", { enumerable: true, get: function () { return multi_tenant_1.isSameTenant; } });
Object.defineProperty(exports, "belongsToOrganization", { enumerable: true, get: function () { return multi_tenant_1.belongsToOrganization; } });
Object.defineProperty(exports, "belongsToClinic", { enumerable: true, get: function () { return multi_tenant_1.belongsToClinic; } });
Object.defineProperty(exports, "canAccessOrganization", { enumerable: true, get: function () { return multi_tenant_1.canAccessOrganization; } });
Object.defineProperty(exports, "canAccessClinic", { enumerable: true, get: function () { return multi_tenant_1.canAccessClinic; } });
Object.defineProperty(exports, "hasOrganizationLevelAccess", { enumerable: true, get: function () { return multi_tenant_1.hasOrganizationLevelAccess; } });
Object.defineProperty(exports, "hasClinicLevelAccess", { enumerable: true, get: function () { return multi_tenant_1.hasClinicLevelAccess; } });
Object.defineProperty(exports, "validateTenantAccess", { enumerable: true, get: function () { return multi_tenant_1.validateTenantAccess; } });
Object.defineProperty(exports, "ensureTenantIsolation", { enumerable: true, get: function () { return multi_tenant_1.ensureTenantIsolation; } });
Object.defineProperty(exports, "validateOrganizationAccess", { enumerable: true, get: function () { return multi_tenant_1.validateOrganizationAccess; } });
Object.defineProperty(exports, "validateClinicAccess", { enumerable: true, get: function () { return multi_tenant_1.validateClinicAccess; } });
Object.defineProperty(exports, "TenantIsolationError", { enumerable: true, get: function () { return multi_tenant_1.TenantIsolationError; } });
var license_1 = require("./license");
Object.defineProperty(exports, "GRACE_PERIOD_DAYS", { enumerable: true, get: function () { return license_1.GRACE_PERIOD_DAYS; } });
Object.defineProperty(exports, "READ_METHODS", { enumerable: true, get: function () { return license_1.READ_METHODS; } });
Object.defineProperty(exports, "WRITE_METHODS", { enumerable: true, get: function () { return license_1.WRITE_METHODS; } });
Object.defineProperty(exports, "CORE_MODULES", { enumerable: true, get: function () { return license_1.CORE_MODULES; } });
Object.defineProperty(exports, "PREMIUM_MODULES", { enumerable: true, get: function () { return license_1.PREMIUM_MODULES; } });
Object.defineProperty(exports, "ALL_MODULES", { enumerable: true, get: function () { return license_1.ALL_MODULES; } });
Object.defineProperty(exports, "isInGracePeriod", { enumerable: true, get: function () { return license_1.isInGracePeriod; } });
Object.defineProperty(exports, "getGracePeriodDaysRemaining", { enumerable: true, get: function () { return license_1.getGracePeriodDaysRemaining; } });
Object.defineProperty(exports, "isGracePeriodExpiringSoon", { enumerable: true, get: function () { return license_1.isGracePeriodExpiringSoon; } });
Object.defineProperty(exports, "isReadOperation", { enumerable: true, get: function () { return license_1.isReadOperation; } });
Object.defineProperty(exports, "isWriteOperation", { enumerable: true, get: function () { return license_1.isWriteOperation; } });
Object.defineProperty(exports, "canPerformOperation", { enumerable: true, get: function () { return license_1.canPerformOperation; } });
Object.defineProperty(exports, "canPerformWriteOperation", { enumerable: true, get: function () { return license_1.canPerformWriteOperation; } });
Object.defineProperty(exports, "calculateGracePeriodEnd", { enumerable: true, get: function () { return license_1.calculateGracePeriodEnd; } });
Object.defineProperty(exports, "getGracePeriodStatusMessage", { enumerable: true, get: function () { return license_1.getGracePeriodStatusMessage; } });
Object.defineProperty(exports, "getModuleDependencies", { enumerable: true, get: function () { return license_1.getModuleDependencies; } });
Object.defineProperty(exports, "getAllModuleDependencies", { enumerable: true, get: function () { return license_1.getAllModuleDependencies; } });
Object.defineProperty(exports, "hasModuleDependencies", { enumerable: true, get: function () { return license_1.hasModuleDependencies; } });
Object.defineProperty(exports, "getMissingDependencies", { enumerable: true, get: function () { return license_1.getMissingDependencies; } });
Object.defineProperty(exports, "getAllMissingDependencies", { enumerable: true, get: function () { return license_1.getAllMissingDependencies; } });
Object.defineProperty(exports, "areDependenciesSatisfied", { enumerable: true, get: function () { return license_1.areDependenciesSatisfied; } });
Object.defineProperty(exports, "getDependencyErrorMessage", { enumerable: true, get: function () { return license_1.getDependencyErrorMessage; } });
Object.defineProperty(exports, "validateModuleDependencies", { enumerable: true, get: function () { return license_1.validateModuleDependencies; } });
Object.defineProperty(exports, "dependsOn", { enumerable: true, get: function () { return license_1.dependsOn; } });
Object.defineProperty(exports, "hasModule", { enumerable: true, get: function () { return license_1.hasModule; } });
Object.defineProperty(exports, "hasAnyModule", { enumerable: true, get: function () { return license_1.hasAnyModule; } });
Object.defineProperty(exports, "hasAllModules", { enumerable: true, get: function () { return license_1.hasAllModules; } });
Object.defineProperty(exports, "getAvailableModules", { enumerable: true, get: function () { return license_1.getAvailableModules; } });
Object.defineProperty(exports, "isSubscriptionActive", { enumerable: true, get: function () { return license_1.isSubscriptionActive; } });
Object.defineProperty(exports, "isInGracePeriodSimple", { enumerable: true, get: function () { return license_1.isInGracePeriodSimple; } });
Object.defineProperty(exports, "hasPremiumAccess", { enumerable: true, get: function () { return license_1.hasPremiumAccess; } });
Object.defineProperty(exports, "hasOnlyCoreModules", { enumerable: true, get: function () { return license_1.hasOnlyCoreModules; } });
Object.defineProperty(exports, "getCoreModules", { enumerable: true, get: function () { return license_1.getCoreModules; } });
Object.defineProperty(exports, "getPremiumModules", { enumerable: true, get: function () { return license_1.getPremiumModules; } });
Object.defineProperty(exports, "canAccessModule", { enumerable: true, get: function () { return license_1.canAccessModule; } });
Object.defineProperty(exports, "getMissingModules", { enumerable: true, get: function () { return license_1.getMissingModules; } });
Object.defineProperty(exports, "isTrialUser", { enumerable: true, get: function () { return license_1.isTrialUser; } });
Object.defineProperty(exports, "isSubscriptionExpired", { enumerable: true, get: function () { return license_1.isSubscriptionExpired; } });
Object.defineProperty(exports, "getSubscriptionStatus", { enumerable: true, get: function () { return license_1.getSubscriptionStatus; } });
Object.defineProperty(exports, "LicenseValidatorService", { enumerable: true, get: function () { return license_1.LicenseValidatorService; } });
Object.defineProperty(exports, "LicenseForbiddenException", { enumerable: true, get: function () { return license_1.LicenseForbiddenException; } });
//# sourceMappingURL=index.js.map