export enum AITaskType {
  CLINICAL_ASSIST = 'CLINICAL_ASSIST',
  CLINICAL_RECOMMENDATION = 'CLINICAL_RECOMMENDATION',
  IMAGING_FINDINGS = 'IMAGING_FINDINGS',
  BILLING_RISK = 'BILLING_RISK',
  FRAUD_SCORE = 'FRAUD_SCORE',
  APPOINTMENT_NO_SHOW = 'APPOINTMENT_NO_SHOW',
  SCHEDULING_RECOMMENDATION = 'SCHEDULING_RECOMMENDATION',
  MARKETING_CHURN = 'MARKETING_CHURN',
  MARKETING_PERSONALIZATION = 'MARKETING_PERSONALIZATION',
  INVENTORY_FORECAST = 'INVENTORY_FORECAST',
  REVENUE_FORECAST = 'REVENUE_FORECAST',
}
