import type { UUID, OrganizationId, ClinicId, ISODateString } from '@dentalos/shared-types';
import type { EventEnvelope } from '../envelope/event-envelope';
export declare const CLINICAL_NOTE_CREATED_EVENT: "dental.clinical.note.created";
export declare const TREATMENT_PLAN_CREATED_EVENT: "dental.clinical.treatment-plan.created";
export declare const TREATMENT_PLAN_UPDATED_EVENT: "dental.clinical.treatment-plan.updated";
export declare const PROCEDURE_COMPLETED_EVENT: "dental.clinical.procedure.completed";
export declare const CONSENT_SIGNED_EVENT: "dental.clinical.consent.signed";
export declare const TOOTH_STATUS_UPDATED_EVENT: "dental.clinical.tooth.status-updated";
export declare const CLINICAL_NOTE_CREATED_VERSION = 1;
export declare const TREATMENT_PLAN_CREATED_VERSION = 1;
export declare const TREATMENT_PLAN_UPDATED_VERSION = 1;
export declare const PROCEDURE_COMPLETED_VERSION = 1;
export declare const CONSENT_SIGNED_VERSION = 1;
export declare const TOOTH_STATUS_UPDATED_VERSION = 1;
export type ClinicalNoteType = 'SOAP' | 'PROGRESS' | 'TREATMENT' | 'CONSULTATION' | 'PROCEDURE' | 'REFERRAL' | 'EMERGENCY' | 'FOLLOW_UP' | 'OTHER';
export type ToothNumberingSystem = 'UNIVERSAL' | 'FDI' | 'PALMER';
export type ToothSurface = 'M' | 'O' | 'D' | 'B' | 'F' | 'L' | 'I';
export type ToothCondition = 'HEALTHY' | 'CARIES' | 'FILLED' | 'CROWN' | 'ROOT_CANAL' | 'IMPLANT' | 'MISSING' | 'EXTRACTED' | 'IMPACTED' | 'FRACTURED' | 'WATCH' | 'OTHER';
export type ConsentType = 'TREATMENT' | 'ANESTHESIA' | 'SURGERY' | 'RADIOGRAPH' | 'MEDICATION' | 'RELEASE_OF_INFORMATION' | 'FINANCIAL' | 'PRIVACY' | 'PHOTOGRAPHY' | 'RESEARCH' | 'OTHER';
export type SignatureMethod = 'ELECTRONIC' | 'HANDWRITTEN' | 'VERBAL' | 'DIGITAL_PAD' | 'OTHER';
export interface StockItemUsed {
    stockItemId: UUID;
    sku?: string;
    itemName: string;
    quantity: number;
    unit: string;
    batchNumber?: string;
    lotNumber?: string;
}
export interface TreatmentPlanChange {
    field: string;
    previousValue?: string | number | boolean | null;
    newValue?: string | number | boolean | null;
    description?: string;
}
export interface ClinicalNoteCreatedPayload {
    noteId: UUID;
    patientId: UUID;
    providerId: UUID;
    organizationId: OrganizationId;
    clinicId: ClinicId;
    tenantId: string;
    noteType: ClinicalNoteType;
    appointmentId?: UUID;
    timestamp: ISODateString;
    title: string;
    summary?: string;
    chiefComplaint?: string;
    diagnosis?: string[];
    treatmentCodes?: string[];
    isFinalized: boolean;
    providerName: string;
    patientName: string;
    createdAt: ISODateString;
    metadata?: Record<string, unknown>;
}
export type ClinicalNoteCreatedEvent = EventEnvelope<ClinicalNoteCreatedPayload>;
export declare function isClinicalNoteCreatedEvent(event: EventEnvelope<unknown>): event is ClinicalNoteCreatedEvent;
export declare function createClinicalNoteCreatedEvent(payload: ClinicalNoteCreatedPayload, metadata: EventEnvelope<unknown>['metadata'], tenantContext: EventEnvelope<unknown>['tenantContext']): ClinicalNoteCreatedEvent;
export interface TreatmentPlanCreatedPayload {
    treatmentPlanId: UUID;
    patientId: UUID;
    providerId: UUID;
    organizationId: OrganizationId;
    clinicId: ClinicId;
    tenantId: string;
    version: number;
    totalCost: number;
    estimatedInsuranceCoverage?: number;
    patientResponsibility?: number;
    estimatedDuration?: number;
    procedureCount: number;
    priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
    status: 'PROPOSED' | 'ACCEPTED' | 'DECLINED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
    title?: string;
    description?: string;
    expectedStartDate?: ISODateString;
    expectedCompletionDate?: ISODateString;
    consentSigned: boolean;
    providerName: string;
    patientName: string;
    timestamp: ISODateString;
    metadata?: Record<string, unknown>;
}
export type TreatmentPlanCreatedEvent = EventEnvelope<TreatmentPlanCreatedPayload>;
export declare function isTreatmentPlanCreatedEvent(event: EventEnvelope<unknown>): event is TreatmentPlanCreatedEvent;
export declare function createTreatmentPlanCreatedEvent(payload: TreatmentPlanCreatedPayload, metadata: EventEnvelope<unknown>['metadata'], tenantContext: EventEnvelope<unknown>['tenantContext']): TreatmentPlanCreatedEvent;
export interface TreatmentPlanUpdatedPayload {
    treatmentPlanId: UUID;
    patientId: UUID;
    organizationId: OrganizationId;
    clinicId: ClinicId;
    tenantId: string;
    version: number;
    previousVersion: number;
    changes: TreatmentPlanChange[];
    updatedBy: UUID;
    updatedByName?: string;
    reason?: string;
    newStatus?: 'PROPOSED' | 'ACCEPTED' | 'DECLINED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
    previousStatus?: 'PROPOSED' | 'ACCEPTED' | 'DECLINED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
    newTotalCost?: number;
    previousTotalCost?: number;
    newProcedureCount?: number;
    previousProcedureCount?: number;
    timestamp: ISODateString;
    metadata?: Record<string, unknown>;
}
export type TreatmentPlanUpdatedEvent = EventEnvelope<TreatmentPlanUpdatedPayload>;
export declare function isTreatmentPlanUpdatedEvent(event: EventEnvelope<unknown>): event is TreatmentPlanUpdatedEvent;
export declare function createTreatmentPlanUpdatedEvent(payload: TreatmentPlanUpdatedPayload, metadata: EventEnvelope<unknown>['metadata'], tenantContext: EventEnvelope<unknown>['tenantContext']): TreatmentPlanUpdatedEvent;
export interface ProcedureCompletedPayload {
    procedureId: UUID;
    patientId: UUID;
    providerId: UUID;
    organizationId: OrganizationId;
    clinicId: ClinicId;
    tenantId: string;
    procedureCode: string;
    procedureName: string;
    tooth?: string | number;
    toothNumberingSystem?: ToothNumberingSystem;
    surfaces?: ToothSurface[];
    quadrant?: 'UL' | 'UR' | 'LL' | 'LR' | 'UPPER' | 'LOWER' | 'FULL';
    stockItemsUsed: StockItemUsed[];
    appointmentId?: UUID;
    treatmentPlanId?: UUID;
    duration?: number;
    feeCharged?: number;
    outcome?: 'SUCCESSFUL' | 'PARTIAL' | 'FAILED' | 'COMPLICATED';
    providerName: string;
    patientName: string;
    requiresFollowUp: boolean;
    followUpDueDate?: ISODateString;
    notes?: string;
    timestamp: ISODateString;
    metadata?: Record<string, unknown>;
}
export type ProcedureCompletedEvent = EventEnvelope<ProcedureCompletedPayload>;
export declare function isProcedureCompletedEvent(event: EventEnvelope<unknown>): event is ProcedureCompletedEvent;
export declare function createProcedureCompletedEvent(payload: ProcedureCompletedPayload, metadata: EventEnvelope<unknown>['metadata'], tenantContext: EventEnvelope<unknown>['tenantContext']): ProcedureCompletedEvent;
export interface ConsentSignedPayload {
    consentId: UUID;
    patientId: UUID;
    organizationId: OrganizationId;
    clinicId: ClinicId;
    tenantId: string;
    consentType: ConsentType;
    consentFormId?: UUID;
    consentFormVersion?: number;
    consentTitle?: string;
    signedBy: UUID;
    signerName: string;
    patientName: string;
    signerRelationship: 'SELF' | 'PARENT' | 'GUARDIAN' | 'LEGAL_REPRESENTATIVE' | 'OTHER';
    signatureMethod: SignatureMethod;
    signature: string;
    ipAddress?: string;
    userAgent?: string;
    location?: {
        latitude?: number;
        longitude?: number;
        address?: string;
    };
    treatmentPlanId?: UUID;
    procedureId?: UUID;
    witnessedBy?: UUID;
    witnessName?: string;
    expiresAt?: ISODateString;
    isRevocable: boolean;
    status: 'ACTIVE' | 'EXPIRED' | 'REVOKED' | 'SUPERSEDED';
    timestamp: ISODateString;
    metadata?: Record<string, unknown>;
}
export type ConsentSignedEvent = EventEnvelope<ConsentSignedPayload>;
export declare function isConsentSignedEvent(event: EventEnvelope<unknown>): event is ConsentSignedEvent;
export declare function createConsentSignedEvent(payload: ConsentSignedPayload, metadata: EventEnvelope<unknown>['metadata'], tenantContext: EventEnvelope<unknown>['tenantContext']): ConsentSignedEvent;
export interface ToothStatusUpdatedPayload {
    patientId: UUID;
    organizationId: OrganizationId;
    clinicId: ClinicId;
    tenantId: string;
    toothNumber: string | number;
    toothNumberingSystem: ToothNumberingSystem;
    previousCondition: ToothCondition;
    newCondition: ToothCondition;
    surfaces?: ToothSurface[];
    updatedBy: UUID;
    updatedByName?: string;
    patientName?: string;
    procedureId?: UUID;
    treatmentPlanId?: UUID;
    appointmentId?: UUID;
    reason?: string;
    notes?: string;
    severity?: 'MILD' | 'MODERATE' | 'SEVERE';
    requiresImmediateAction: boolean;
    timestamp: ISODateString;
    metadata?: Record<string, unknown>;
}
export type ToothStatusUpdatedEvent = EventEnvelope<ToothStatusUpdatedPayload>;
export declare function isToothStatusUpdatedEvent(event: EventEnvelope<unknown>): event is ToothStatusUpdatedEvent;
export declare function createToothStatusUpdatedEvent(payload: ToothStatusUpdatedPayload, metadata: EventEnvelope<unknown>['metadata'], tenantContext: EventEnvelope<unknown>['tenantContext']): ToothStatusUpdatedEvent;
