"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.QueryImagingReportsDtoSchema = exports.UpdateImagingReportDtoSchema = exports.CreateImagingReportDtoSchema = exports.ReportStatusSchema = exports.ReportTypeSchema = exports.AttachAIResultDtoSchema = exports.AIFindingSchema = exports.FindingSeveritySchema = exports.FindingTypeSchema = exports.BoundingBoxSchema = exports.AttachFilesToStudyDtoSchema = exports.ImagingFileSchema = exports.DicomMetadataSchema = exports.QueryImagingStudiesDtoSchema = exports.UpdateImagingStudyDtoSchema = exports.CreateImagingStudyDtoSchema = exports.ToothNumbersArraySchema = exports.ImagingStudyStatusSchema = exports.ImagingRegionSchema = exports.ImagingModalitySchema = exports.ReportStatus = exports.ReportType = exports.FindingSeverity = exports.FindingType = exports.ImagingStudyStatus = exports.ImagingRegion = exports.ImagingModality = void 0;
var imaging_schemas_1 = require("./imaging.schemas");
Object.defineProperty(exports, "ImagingModality", { enumerable: true, get: function () { return imaging_schemas_1.ImagingModality; } });
Object.defineProperty(exports, "ImagingRegion", { enumerable: true, get: function () { return imaging_schemas_1.ImagingRegion; } });
Object.defineProperty(exports, "ImagingStudyStatus", { enumerable: true, get: function () { return imaging_schemas_1.ImagingStudyStatus; } });
Object.defineProperty(exports, "FindingType", { enumerable: true, get: function () { return imaging_schemas_1.FindingType; } });
Object.defineProperty(exports, "FindingSeverity", { enumerable: true, get: function () { return imaging_schemas_1.FindingSeverity; } });
Object.defineProperty(exports, "ReportType", { enumerable: true, get: function () { return imaging_schemas_1.ReportType; } });
Object.defineProperty(exports, "ReportStatus", { enumerable: true, get: function () { return imaging_schemas_1.ReportStatus; } });
Object.defineProperty(exports, "ImagingModalitySchema", { enumerable: true, get: function () { return imaging_schemas_1.ImagingModalitySchema; } });
Object.defineProperty(exports, "ImagingRegionSchema", { enumerable: true, get: function () { return imaging_schemas_1.ImagingRegionSchema; } });
Object.defineProperty(exports, "ImagingStudyStatusSchema", { enumerable: true, get: function () { return imaging_schemas_1.ImagingStudyStatusSchema; } });
Object.defineProperty(exports, "ToothNumbersArraySchema", { enumerable: true, get: function () { return imaging_schemas_1.ToothNumbersArraySchema; } });
Object.defineProperty(exports, "CreateImagingStudyDtoSchema", { enumerable: true, get: function () { return imaging_schemas_1.CreateImagingStudyDtoSchema; } });
Object.defineProperty(exports, "UpdateImagingStudyDtoSchema", { enumerable: true, get: function () { return imaging_schemas_1.UpdateImagingStudyDtoSchema; } });
Object.defineProperty(exports, "QueryImagingStudiesDtoSchema", { enumerable: true, get: function () { return imaging_schemas_1.QueryImagingStudiesDtoSchema; } });
Object.defineProperty(exports, "DicomMetadataSchema", { enumerable: true, get: function () { return imaging_schemas_1.DicomMetadataSchema; } });
Object.defineProperty(exports, "ImagingFileSchema", { enumerable: true, get: function () { return imaging_schemas_1.ImagingFileSchema; } });
Object.defineProperty(exports, "AttachFilesToStudyDtoSchema", { enumerable: true, get: function () { return imaging_schemas_1.AttachFilesToStudyDtoSchema; } });
Object.defineProperty(exports, "BoundingBoxSchema", { enumerable: true, get: function () { return imaging_schemas_1.BoundingBoxSchema; } });
Object.defineProperty(exports, "FindingTypeSchema", { enumerable: true, get: function () { return imaging_schemas_1.FindingTypeSchema; } });
Object.defineProperty(exports, "FindingSeveritySchema", { enumerable: true, get: function () { return imaging_schemas_1.FindingSeveritySchema; } });
Object.defineProperty(exports, "AIFindingSchema", { enumerable: true, get: function () { return imaging_schemas_1.AIFindingSchema; } });
Object.defineProperty(exports, "AttachAIResultDtoSchema", { enumerable: true, get: function () { return imaging_schemas_1.AttachAIResultDtoSchema; } });
Object.defineProperty(exports, "ReportTypeSchema", { enumerable: true, get: function () { return imaging_schemas_1.ReportTypeSchema; } });
Object.defineProperty(exports, "ReportStatusSchema", { enumerable: true, get: function () { return imaging_schemas_1.ReportStatusSchema; } });
Object.defineProperty(exports, "CreateImagingReportDtoSchema", { enumerable: true, get: function () { return imaging_schemas_1.CreateImagingReportDtoSchema; } });
Object.defineProperty(exports, "UpdateImagingReportDtoSchema", { enumerable: true, get: function () { return imaging_schemas_1.UpdateImagingReportDtoSchema; } });
Object.defineProperty(exports, "QueryImagingReportsDtoSchema", { enumerable: true, get: function () { return imaging_schemas_1.QueryImagingReportsDtoSchema; } });
//# sourceMappingURL=index.js.map