"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReviewAbsenceDtoSchema = exports.UpdateProviderAbsenceDtoSchema = exports.CreateProviderAbsenceDtoSchema = exports.CreateScheduleExceptionDtoSchema = exports.UpdateWeeklyHoursDtoSchema = exports.CreateWeeklyHoursDtoSchema = exports.BulkScheduleUpdateSchema = exports.AvailabilitySummarySchema = exports.AvailableSlotSchema = exports.AvailabilitySearchCriteriaSchema = exports.ProviderScheduleSchema = exports.ProviderAbsenceSchema = exports.ScheduleExceptionSchema = exports.WeeklyHoursSchema = exports.TimeSlotSchema = exports.DailyWorkingHoursSchema = exports.WorkPeriodSchema = exports.TimeOfDaySchema = exports.ScheduleExceptionTypeSchema = exports.ScheduleRecurrenceSchema = exports.AbsenceStatusSchema = exports.AbsenceTypeSchema = exports.TimeSlotTypeSchema = exports.DayOfWeekSchema = exports.CompleteAppointmentDtoSchema = exports.RescheduleAppointmentDtoSchema = exports.CancelAppointmentDtoSchema = exports.CheckInAppointmentDtoSchema = exports.ConfirmAppointmentDtoSchema = exports.AppointmentQueryDtoSchema = exports.UpdateAppointmentDtoSchema = exports.CreateAppointmentDtoSchema = exports.AppointmentSchema = exports.CompletionDetailsSchema = exports.CheckInDetailsSchema = exports.ConfirmationDetailsSchema = exports.CancellationDetailsSchema = exports.ResourceAllocationSchema = exports.BookingMetadataSchema = exports.AppointmentNoteSchema = exports.RecurrenceRuleSchema = exports.AppointmentParticipantSchema = exports.RecurrencePatternSchema = exports.ConfirmationMethodSchema = exports.CheckInMethodSchema = exports.BookingSourceSchema = exports.ParticipantRoleSchema = exports.AppointmentPrioritySchema = exports.CancellationTypeSchema = exports.AppointmentStatusSchema = void 0;
exports.UpdateProviderScheduleDtoSchema = exports.CreateProviderScheduleDtoSchema = void 0;
var appointment_schemas_1 = require("./appointment.schemas");
Object.defineProperty(exports, "AppointmentStatusSchema", { enumerable: true, get: function () { return appointment_schemas_1.AppointmentStatusSchema; } });
Object.defineProperty(exports, "CancellationTypeSchema", { enumerable: true, get: function () { return appointment_schemas_1.CancellationTypeSchema; } });
Object.defineProperty(exports, "AppointmentPrioritySchema", { enumerable: true, get: function () { return appointment_schemas_1.AppointmentPrioritySchema; } });
Object.defineProperty(exports, "ParticipantRoleSchema", { enumerable: true, get: function () { return appointment_schemas_1.ParticipantRoleSchema; } });
Object.defineProperty(exports, "BookingSourceSchema", { enumerable: true, get: function () { return appointment_schemas_1.BookingSourceSchema; } });
Object.defineProperty(exports, "CheckInMethodSchema", { enumerable: true, get: function () { return appointment_schemas_1.CheckInMethodSchema; } });
Object.defineProperty(exports, "ConfirmationMethodSchema", { enumerable: true, get: function () { return appointment_schemas_1.ConfirmationMethodSchema; } });
Object.defineProperty(exports, "RecurrencePatternSchema", { enumerable: true, get: function () { return appointment_schemas_1.RecurrencePatternSchema; } });
Object.defineProperty(exports, "AppointmentParticipantSchema", { enumerable: true, get: function () { return appointment_schemas_1.AppointmentParticipantSchema; } });
Object.defineProperty(exports, "RecurrenceRuleSchema", { enumerable: true, get: function () { return appointment_schemas_1.RecurrenceRuleSchema; } });
Object.defineProperty(exports, "AppointmentNoteSchema", { enumerable: true, get: function () { return appointment_schemas_1.AppointmentNoteSchema; } });
Object.defineProperty(exports, "BookingMetadataSchema", { enumerable: true, get: function () { return appointment_schemas_1.BookingMetadataSchema; } });
Object.defineProperty(exports, "ResourceAllocationSchema", { enumerable: true, get: function () { return appointment_schemas_1.ResourceAllocationSchema; } });
Object.defineProperty(exports, "CancellationDetailsSchema", { enumerable: true, get: function () { return appointment_schemas_1.CancellationDetailsSchema; } });
Object.defineProperty(exports, "ConfirmationDetailsSchema", { enumerable: true, get: function () { return appointment_schemas_1.ConfirmationDetailsSchema; } });
Object.defineProperty(exports, "CheckInDetailsSchema", { enumerable: true, get: function () { return appointment_schemas_1.CheckInDetailsSchema; } });
Object.defineProperty(exports, "CompletionDetailsSchema", { enumerable: true, get: function () { return appointment_schemas_1.CompletionDetailsSchema; } });
Object.defineProperty(exports, "AppointmentSchema", { enumerable: true, get: function () { return appointment_schemas_1.AppointmentSchema; } });
Object.defineProperty(exports, "CreateAppointmentDtoSchema", { enumerable: true, get: function () { return appointment_schemas_1.CreateAppointmentDtoSchema; } });
Object.defineProperty(exports, "UpdateAppointmentDtoSchema", { enumerable: true, get: function () { return appointment_schemas_1.UpdateAppointmentDtoSchema; } });
Object.defineProperty(exports, "AppointmentQueryDtoSchema", { enumerable: true, get: function () { return appointment_schemas_1.AppointmentQueryDtoSchema; } });
Object.defineProperty(exports, "ConfirmAppointmentDtoSchema", { enumerable: true, get: function () { return appointment_schemas_1.ConfirmAppointmentDtoSchema; } });
Object.defineProperty(exports, "CheckInAppointmentDtoSchema", { enumerable: true, get: function () { return appointment_schemas_1.CheckInAppointmentDtoSchema; } });
Object.defineProperty(exports, "CancelAppointmentDtoSchema", { enumerable: true, get: function () { return appointment_schemas_1.CancelAppointmentDtoSchema; } });
Object.defineProperty(exports, "RescheduleAppointmentDtoSchema", { enumerable: true, get: function () { return appointment_schemas_1.RescheduleAppointmentDtoSchema; } });
Object.defineProperty(exports, "CompleteAppointmentDtoSchema", { enumerable: true, get: function () { return appointment_schemas_1.CompleteAppointmentDtoSchema; } });
var provider_schedule_schemas_1 = require("./provider-schedule.schemas");
Object.defineProperty(exports, "DayOfWeekSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.DayOfWeekSchema; } });
Object.defineProperty(exports, "TimeSlotTypeSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.TimeSlotTypeSchema; } });
Object.defineProperty(exports, "AbsenceTypeSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.AbsenceTypeSchema; } });
Object.defineProperty(exports, "AbsenceStatusSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.AbsenceStatusSchema; } });
Object.defineProperty(exports, "ScheduleRecurrenceSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.ScheduleRecurrenceSchema; } });
Object.defineProperty(exports, "ScheduleExceptionTypeSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.ScheduleExceptionTypeSchema; } });
Object.defineProperty(exports, "TimeOfDaySchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.TimeOfDaySchema; } });
Object.defineProperty(exports, "WorkPeriodSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.WorkPeriodSchema; } });
Object.defineProperty(exports, "DailyWorkingHoursSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.DailyWorkingHoursSchema; } });
Object.defineProperty(exports, "TimeSlotSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.TimeSlotSchema; } });
Object.defineProperty(exports, "WeeklyHoursSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.WeeklyHoursSchema; } });
Object.defineProperty(exports, "ScheduleExceptionSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.ScheduleExceptionSchema; } });
Object.defineProperty(exports, "ProviderAbsenceSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.ProviderAbsenceSchema; } });
Object.defineProperty(exports, "ProviderScheduleSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.ProviderScheduleSchema; } });
Object.defineProperty(exports, "AvailabilitySearchCriteriaSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.AvailabilitySearchCriteriaSchema; } });
Object.defineProperty(exports, "AvailableSlotSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.AvailableSlotSchema; } });
Object.defineProperty(exports, "AvailabilitySummarySchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.AvailabilitySummarySchema; } });
Object.defineProperty(exports, "BulkScheduleUpdateSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.BulkScheduleUpdateSchema; } });
Object.defineProperty(exports, "CreateWeeklyHoursDtoSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.CreateWeeklyHoursDtoSchema; } });
Object.defineProperty(exports, "UpdateWeeklyHoursDtoSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.UpdateWeeklyHoursDtoSchema; } });
Object.defineProperty(exports, "CreateScheduleExceptionDtoSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.CreateScheduleExceptionDtoSchema; } });
Object.defineProperty(exports, "CreateProviderAbsenceDtoSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.CreateProviderAbsenceDtoSchema; } });
Object.defineProperty(exports, "UpdateProviderAbsenceDtoSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.UpdateProviderAbsenceDtoSchema; } });
Object.defineProperty(exports, "ReviewAbsenceDtoSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.ReviewAbsenceDtoSchema; } });
Object.defineProperty(exports, "CreateProviderScheduleDtoSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.CreateProviderScheduleDtoSchema; } });
Object.defineProperty(exports, "UpdateProviderScheduleDtoSchema", { enumerable: true, get: function () { return provider_schedule_schemas_1.UpdateProviderScheduleDtoSchema; } });
//# sourceMappingURL=index.js.map