"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TenantIsolationError = exports.validateClinicAccess = exports.canAccessClinicValidator = exports.validateOrganizationAccess = exports.canAccessOrganizationValidator = exports.ensureTenantIsolation = exports.validateTenantAccess = exports.hasClinicLevelAccess = exports.hasOrganizationLevelAccess = exports.canAccessClinic = exports.canAccessOrganization = exports.belongsToClinic = exports.belongsToOrganization = exports.isSameTenant = void 0;
var tenant_checker_1 = require("./tenant-checker");
Object.defineProperty(exports, "isSameTenant", { enumerable: true, get: function () { return tenant_checker_1.isSameTenant; } });
Object.defineProperty(exports, "belongsToOrganization", { enumerable: true, get: function () { return tenant_checker_1.belongsToOrganization; } });
Object.defineProperty(exports, "belongsToClinic", { enumerable: true, get: function () { return tenant_checker_1.belongsToClinic; } });
Object.defineProperty(exports, "canAccessOrganization", { enumerable: true, get: function () { return tenant_checker_1.canAccessOrganization; } });
Object.defineProperty(exports, "canAccessClinic", { enumerable: true, get: function () { return tenant_checker_1.canAccessClinic; } });
Object.defineProperty(exports, "hasOrganizationLevelAccess", { enumerable: true, get: function () { return tenant_checker_1.hasOrganizationLevelAccess; } });
Object.defineProperty(exports, "hasClinicLevelAccess", { enumerable: true, get: function () { return tenant_checker_1.hasClinicLevelAccess; } });
var tenant_validators_1 = require("./tenant-validators");
Object.defineProperty(exports, "validateTenantAccess", { enumerable: true, get: function () { return tenant_validators_1.validateTenantAccess; } });
Object.defineProperty(exports, "ensureTenantIsolation", { enumerable: true, get: function () { return tenant_validators_1.ensureTenantIsolation; } });
Object.defineProperty(exports, "canAccessOrganizationValidator", { enumerable: true, get: function () { return tenant_validators_1.canAccessOrganization; } });
Object.defineProperty(exports, "validateOrganizationAccess", { enumerable: true, get: function () { return tenant_validators_1.validateOrganizationAccess; } });
Object.defineProperty(exports, "canAccessClinicValidator", { enumerable: true, get: function () { return tenant_validators_1.canAccessClinic; } });
Object.defineProperty(exports, "validateClinicAccess", { enumerable: true, get: function () { return tenant_validators_1.validateClinicAccess; } });
Object.defineProperty(exports, "TenantIsolationError", { enumerable: true, get: function () { return tenant_validators_1.TenantIsolationError; } });
//# sourceMappingURL=index.js.map