import { OrganizationId, ClinicId } from '@dentalos/shared-types';
import { CurrentTenant } from '../context/current-tenant';
import { CurrentUser } from '../context/current-user';
export declare function isSameTenant(context1: CurrentTenant, context2: CurrentTenant): boolean;
export declare function belongsToOrganization(context: CurrentTenant, organizationId: OrganizationId): boolean;
export declare function belongsToClinic(context: CurrentTenant, clinicId: ClinicId): boolean;
export declare function canAccessOrganization(user: CurrentUser, organizationId: OrganizationId): boolean;
export declare function canAccessClinic(user: CurrentUser, clinicId: ClinicId): boolean;
export declare function hasOrganizationLevelAccess(user: CurrentUser): boolean;
export declare function hasClinicLevelAccess(user: CurrentUser): boolean;
