"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LOYALTY_POINTS_ACCRUED_VERSION = exports.LOYALTY_ACCOUNT_CREATED_VERSION = exports.REFERRAL_EXPIRED_VERSION = exports.REFERRAL_REDEEMED_VERSION = exports.REFERRAL_COMPLETED_VERSION = exports.REFERRAL_CREATED_VERSION = exports.SEGMENT_PATIENT_REMOVED_VERSION = exports.SEGMENT_PATIENT_ADDED_VERSION = exports.SEGMENT_REFRESHED_VERSION = exports.SEGMENT_CREATED_VERSION = exports.CAMPAIGN_UNSUBSCRIBED_VERSION = exports.CAMPAIGN_CLICKED_VERSION = exports.CAMPAIGN_OPENED_VERSION = exports.CAMPAIGN_DELIVERED_VERSION = exports.CAMPAIGN_TRIGGERED_VERSION = exports.CAMPAIGN_UPDATED_VERSION = exports.CAMPAIGN_CREATED_VERSION = exports.DELIVERY_BOUNCED = exports.DELIVERY_FAILED = exports.DELIVERY_SENT = exports.DELIVERY_QUEUED = exports.AUTOMATION_EXECUTED = exports.AUTOMATION_TRIGGERED = exports.NPS_DETRACTOR = exports.NPS_PROMOTER = exports.NPS_SUBMITTED = exports.FEEDBACK_NEGATIVE = exports.FEEDBACK_POSITIVE = exports.FEEDBACK_RECEIVED = exports.LOYALTY_TIER_DOWNGRADED = exports.LOYALTY_TIER_UPGRADED = exports.LOYALTY_POINTS_EXPIRED = exports.LOYALTY_POINTS_REDEEMED = exports.LOYALTY_POINTS_ACCRUED = exports.LOYALTY_ACCOUNT_CREATED = exports.REFERRAL_EXPIRED = exports.REFERRAL_REDEEMED = exports.REFERRAL_COMPLETED = exports.REFERRAL_CREATED = exports.SEGMENT_PATIENT_REMOVED = exports.SEGMENT_PATIENT_ADDED = exports.SEGMENT_REFRESHED = exports.SEGMENT_CREATED = exports.CAMPAIGN_UNSUBSCRIBED = exports.CAMPAIGN_CLICKED = exports.CAMPAIGN_OPENED = exports.CAMPAIGN_DELIVERED = exports.CAMPAIGN_TRIGGERED = exports.CAMPAIGN_UPDATED = exports.CAMPAIGN_CREATED = void 0;
exports.DELIVERY_BOUNCED_VERSION = exports.DELIVERY_FAILED_VERSION = exports.DELIVERY_SENT_VERSION = exports.DELIVERY_QUEUED_VERSION = exports.AUTOMATION_EXECUTED_VERSION = exports.AUTOMATION_TRIGGERED_VERSION = exports.NPS_DETRACTOR_VERSION = exports.NPS_PROMOTER_VERSION = exports.NPS_SUBMITTED_VERSION = exports.FEEDBACK_NEGATIVE_VERSION = exports.FEEDBACK_POSITIVE_VERSION = exports.FEEDBACK_RECEIVED_VERSION = exports.LOYALTY_TIER_DOWNGRADED_VERSION = exports.LOYALTY_TIER_UPGRADED_VERSION = exports.LOYALTY_POINTS_EXPIRED_VERSION = exports.LOYALTY_POINTS_REDEEMED_VERSION = void 0;
var marketing_events_1 = require("./marketing.events");
Object.defineProperty(exports, "CAMPAIGN_CREATED", { enumerable: true, get: function () { return marketing_events_1.CAMPAIGN_CREATED; } });
Object.defineProperty(exports, "CAMPAIGN_UPDATED", { enumerable: true, get: function () { return marketing_events_1.CAMPAIGN_UPDATED; } });
Object.defineProperty(exports, "CAMPAIGN_TRIGGERED", { enumerable: true, get: function () { return marketing_events_1.CAMPAIGN_TRIGGERED; } });
Object.defineProperty(exports, "CAMPAIGN_DELIVERED", { enumerable: true, get: function () { return marketing_events_1.CAMPAIGN_DELIVERED; } });
Object.defineProperty(exports, "CAMPAIGN_OPENED", { enumerable: true, get: function () { return marketing_events_1.CAMPAIGN_OPENED; } });
Object.defineProperty(exports, "CAMPAIGN_CLICKED", { enumerable: true, get: function () { return marketing_events_1.CAMPAIGN_CLICKED; } });
Object.defineProperty(exports, "CAMPAIGN_UNSUBSCRIBED", { enumerable: true, get: function () { return marketing_events_1.CAMPAIGN_UNSUBSCRIBED; } });
Object.defineProperty(exports, "SEGMENT_CREATED", { enumerable: true, get: function () { return marketing_events_1.SEGMENT_CREATED; } });
Object.defineProperty(exports, "SEGMENT_REFRESHED", { enumerable: true, get: function () { return marketing_events_1.SEGMENT_REFRESHED; } });
Object.defineProperty(exports, "SEGMENT_PATIENT_ADDED", { enumerable: true, get: function () { return marketing_events_1.SEGMENT_PATIENT_ADDED; } });
Object.defineProperty(exports, "SEGMENT_PATIENT_REMOVED", { enumerable: true, get: function () { return marketing_events_1.SEGMENT_PATIENT_REMOVED; } });
Object.defineProperty(exports, "REFERRAL_CREATED", { enumerable: true, get: function () { return marketing_events_1.REFERRAL_CREATED; } });
Object.defineProperty(exports, "REFERRAL_COMPLETED", { enumerable: true, get: function () { return marketing_events_1.REFERRAL_COMPLETED; } });
Object.defineProperty(exports, "REFERRAL_REDEEMED", { enumerable: true, get: function () { return marketing_events_1.REFERRAL_REDEEMED; } });
Object.defineProperty(exports, "REFERRAL_EXPIRED", { enumerable: true, get: function () { return marketing_events_1.REFERRAL_EXPIRED; } });
Object.defineProperty(exports, "LOYALTY_ACCOUNT_CREATED", { enumerable: true, get: function () { return marketing_events_1.LOYALTY_ACCOUNT_CREATED; } });
Object.defineProperty(exports, "LOYALTY_POINTS_ACCRUED", { enumerable: true, get: function () { return marketing_events_1.LOYALTY_POINTS_ACCRUED; } });
Object.defineProperty(exports, "LOYALTY_POINTS_REDEEMED", { enumerable: true, get: function () { return marketing_events_1.LOYALTY_POINTS_REDEEMED; } });
Object.defineProperty(exports, "LOYALTY_POINTS_EXPIRED", { enumerable: true, get: function () { return marketing_events_1.LOYALTY_POINTS_EXPIRED; } });
Object.defineProperty(exports, "LOYALTY_TIER_UPGRADED", { enumerable: true, get: function () { return marketing_events_1.LOYALTY_TIER_UPGRADED; } });
Object.defineProperty(exports, "LOYALTY_TIER_DOWNGRADED", { enumerable: true, get: function () { return marketing_events_1.LOYALTY_TIER_DOWNGRADED; } });
Object.defineProperty(exports, "FEEDBACK_RECEIVED", { enumerable: true, get: function () { return marketing_events_1.FEEDBACK_RECEIVED; } });
Object.defineProperty(exports, "FEEDBACK_POSITIVE", { enumerable: true, get: function () { return marketing_events_1.FEEDBACK_POSITIVE; } });
Object.defineProperty(exports, "FEEDBACK_NEGATIVE", { enumerable: true, get: function () { return marketing_events_1.FEEDBACK_NEGATIVE; } });
Object.defineProperty(exports, "NPS_SUBMITTED", { enumerable: true, get: function () { return marketing_events_1.NPS_SUBMITTED; } });
Object.defineProperty(exports, "NPS_PROMOTER", { enumerable: true, get: function () { return marketing_events_1.NPS_PROMOTER; } });
Object.defineProperty(exports, "NPS_DETRACTOR", { enumerable: true, get: function () { return marketing_events_1.NPS_DETRACTOR; } });
Object.defineProperty(exports, "AUTOMATION_TRIGGERED", { enumerable: true, get: function () { return marketing_events_1.AUTOMATION_TRIGGERED; } });
Object.defineProperty(exports, "AUTOMATION_EXECUTED", { enumerable: true, get: function () { return marketing_events_1.AUTOMATION_EXECUTED; } });
Object.defineProperty(exports, "DELIVERY_QUEUED", { enumerable: true, get: function () { return marketing_events_1.DELIVERY_QUEUED; } });
Object.defineProperty(exports, "DELIVERY_SENT", { enumerable: true, get: function () { return marketing_events_1.DELIVERY_SENT; } });
Object.defineProperty(exports, "DELIVERY_FAILED", { enumerable: true, get: function () { return marketing_events_1.DELIVERY_FAILED; } });
Object.defineProperty(exports, "DELIVERY_BOUNCED", { enumerable: true, get: function () { return marketing_events_1.DELIVERY_BOUNCED; } });
var marketing_events_2 = require("./marketing.events");
Object.defineProperty(exports, "CAMPAIGN_CREATED_VERSION", { enumerable: true, get: function () { return marketing_events_2.CAMPAIGN_CREATED_VERSION; } });
Object.defineProperty(exports, "CAMPAIGN_UPDATED_VERSION", { enumerable: true, get: function () { return marketing_events_2.CAMPAIGN_UPDATED_VERSION; } });
Object.defineProperty(exports, "CAMPAIGN_TRIGGERED_VERSION", { enumerable: true, get: function () { return marketing_events_2.CAMPAIGN_TRIGGERED_VERSION; } });
Object.defineProperty(exports, "CAMPAIGN_DELIVERED_VERSION", { enumerable: true, get: function () { return marketing_events_2.CAMPAIGN_DELIVERED_VERSION; } });
Object.defineProperty(exports, "CAMPAIGN_OPENED_VERSION", { enumerable: true, get: function () { return marketing_events_2.CAMPAIGN_OPENED_VERSION; } });
Object.defineProperty(exports, "CAMPAIGN_CLICKED_VERSION", { enumerable: true, get: function () { return marketing_events_2.CAMPAIGN_CLICKED_VERSION; } });
Object.defineProperty(exports, "CAMPAIGN_UNSUBSCRIBED_VERSION", { enumerable: true, get: function () { return marketing_events_2.CAMPAIGN_UNSUBSCRIBED_VERSION; } });
Object.defineProperty(exports, "SEGMENT_CREATED_VERSION", { enumerable: true, get: function () { return marketing_events_2.SEGMENT_CREATED_VERSION; } });
Object.defineProperty(exports, "SEGMENT_REFRESHED_VERSION", { enumerable: true, get: function () { return marketing_events_2.SEGMENT_REFRESHED_VERSION; } });
Object.defineProperty(exports, "SEGMENT_PATIENT_ADDED_VERSION", { enumerable: true, get: function () { return marketing_events_2.SEGMENT_PATIENT_ADDED_VERSION; } });
Object.defineProperty(exports, "SEGMENT_PATIENT_REMOVED_VERSION", { enumerable: true, get: function () { return marketing_events_2.SEGMENT_PATIENT_REMOVED_VERSION; } });
Object.defineProperty(exports, "REFERRAL_CREATED_VERSION", { enumerable: true, get: function () { return marketing_events_2.REFERRAL_CREATED_VERSION; } });
Object.defineProperty(exports, "REFERRAL_COMPLETED_VERSION", { enumerable: true, get: function () { return marketing_events_2.REFERRAL_COMPLETED_VERSION; } });
Object.defineProperty(exports, "REFERRAL_REDEEMED_VERSION", { enumerable: true, get: function () { return marketing_events_2.REFERRAL_REDEEMED_VERSION; } });
Object.defineProperty(exports, "REFERRAL_EXPIRED_VERSION", { enumerable: true, get: function () { return marketing_events_2.REFERRAL_EXPIRED_VERSION; } });
Object.defineProperty(exports, "LOYALTY_ACCOUNT_CREATED_VERSION", { enumerable: true, get: function () { return marketing_events_2.LOYALTY_ACCOUNT_CREATED_VERSION; } });
Object.defineProperty(exports, "LOYALTY_POINTS_ACCRUED_VERSION", { enumerable: true, get: function () { return marketing_events_2.LOYALTY_POINTS_ACCRUED_VERSION; } });
Object.defineProperty(exports, "LOYALTY_POINTS_REDEEMED_VERSION", { enumerable: true, get: function () { return marketing_events_2.LOYALTY_POINTS_REDEEMED_VERSION; } });
Object.defineProperty(exports, "LOYALTY_POINTS_EXPIRED_VERSION", { enumerable: true, get: function () { return marketing_events_2.LOYALTY_POINTS_EXPIRED_VERSION; } });
Object.defineProperty(exports, "LOYALTY_TIER_UPGRADED_VERSION", { enumerable: true, get: function () { return marketing_events_2.LOYALTY_TIER_UPGRADED_VERSION; } });
Object.defineProperty(exports, "LOYALTY_TIER_DOWNGRADED_VERSION", { enumerable: true, get: function () { return marketing_events_2.LOYALTY_TIER_DOWNGRADED_VERSION; } });
Object.defineProperty(exports, "FEEDBACK_RECEIVED_VERSION", { enumerable: true, get: function () { return marketing_events_2.FEEDBACK_RECEIVED_VERSION; } });
Object.defineProperty(exports, "FEEDBACK_POSITIVE_VERSION", { enumerable: true, get: function () { return marketing_events_2.FEEDBACK_POSITIVE_VERSION; } });
Object.defineProperty(exports, "FEEDBACK_NEGATIVE_VERSION", { enumerable: true, get: function () { return marketing_events_2.FEEDBACK_NEGATIVE_VERSION; } });
Object.defineProperty(exports, "NPS_SUBMITTED_VERSION", { enumerable: true, get: function () { return marketing_events_2.NPS_SUBMITTED_VERSION; } });
Object.defineProperty(exports, "NPS_PROMOTER_VERSION", { enumerable: true, get: function () { return marketing_events_2.NPS_PROMOTER_VERSION; } });
Object.defineProperty(exports, "NPS_DETRACTOR_VERSION", { enumerable: true, get: function () { return marketing_events_2.NPS_DETRACTOR_VERSION; } });
Object.defineProperty(exports, "AUTOMATION_TRIGGERED_VERSION", { enumerable: true, get: function () { return marketing_events_2.AUTOMATION_TRIGGERED_VERSION; } });
Object.defineProperty(exports, "AUTOMATION_EXECUTED_VERSION", { enumerable: true, get: function () { return marketing_events_2.AUTOMATION_EXECUTED_VERSION; } });
Object.defineProperty(exports, "DELIVERY_QUEUED_VERSION", { enumerable: true, get: function () { return marketing_events_2.DELIVERY_QUEUED_VERSION; } });
Object.defineProperty(exports, "DELIVERY_SENT_VERSION", { enumerable: true, get: function () { return marketing_events_2.DELIVERY_SENT_VERSION; } });
Object.defineProperty(exports, "DELIVERY_FAILED_VERSION", { enumerable: true, get: function () { return marketing_events_2.DELIVERY_FAILED_VERSION; } });
Object.defineProperty(exports, "DELIVERY_BOUNCED_VERSION", { enumerable: true, get: function () { return marketing_events_2.DELIVERY_BOUNCED_VERSION; } });
//# sourceMappingURL=index.js.map