"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createGoodsReceiptCreatedEvent = exports.createPurchaseOrderCreatedEvent = exports.createStockExpiredEvent = exports.createStockLowEvent = exports.createStockRestockedEvent = exports.createStockDeductedEvent = exports.isGoodsReceiptCreatedEvent = exports.isPurchaseOrderCreatedEvent = exports.isStockExpiredEvent = exports.isStockLowEvent = exports.isStockRestockedEvent = exports.isStockDeductedEvent = exports.GOODS_RECEIPT_CREATED_VERSION = exports.PURCHASE_ORDER_CREATED_VERSION = exports.STOCK_EXPIRED_VERSION = exports.STOCK_LOW_VERSION = exports.STOCK_RESTOCKED_VERSION = exports.STOCK_DEDUCTED_VERSION = exports.GOODS_RECEIPT_CREATED_EVENT = exports.PURCHASE_ORDER_CREATED_EVENT = exports.STOCK_EXPIRED_EVENT = exports.STOCK_LOW_EVENT = exports.STOCK_RESTOCKED_EVENT = exports.STOCK_DEDUCTED_EVENT = void 0;
var inventory_events_1 = require("./inventory.events");
Object.defineProperty(exports, "STOCK_DEDUCTED_EVENT", { enumerable: true, get: function () { return inventory_events_1.STOCK_DEDUCTED_EVENT; } });
Object.defineProperty(exports, "STOCK_RESTOCKED_EVENT", { enumerable: true, get: function () { return inventory_events_1.STOCK_RESTOCKED_EVENT; } });
Object.defineProperty(exports, "STOCK_LOW_EVENT", { enumerable: true, get: function () { return inventory_events_1.STOCK_LOW_EVENT; } });
Object.defineProperty(exports, "STOCK_EXPIRED_EVENT", { enumerable: true, get: function () { return inventory_events_1.STOCK_EXPIRED_EVENT; } });
Object.defineProperty(exports, "PURCHASE_ORDER_CREATED_EVENT", { enumerable: true, get: function () { return inventory_events_1.PURCHASE_ORDER_CREATED_EVENT; } });
Object.defineProperty(exports, "GOODS_RECEIPT_CREATED_EVENT", { enumerable: true, get: function () { return inventory_events_1.GOODS_RECEIPT_CREATED_EVENT; } });
var inventory_events_2 = require("./inventory.events");
Object.defineProperty(exports, "STOCK_DEDUCTED_VERSION", { enumerable: true, get: function () { return inventory_events_2.STOCK_DEDUCTED_VERSION; } });
Object.defineProperty(exports, "STOCK_RESTOCKED_VERSION", { enumerable: true, get: function () { return inventory_events_2.STOCK_RESTOCKED_VERSION; } });
Object.defineProperty(exports, "STOCK_LOW_VERSION", { enumerable: true, get: function () { return inventory_events_2.STOCK_LOW_VERSION; } });
Object.defineProperty(exports, "STOCK_EXPIRED_VERSION", { enumerable: true, get: function () { return inventory_events_2.STOCK_EXPIRED_VERSION; } });
Object.defineProperty(exports, "PURCHASE_ORDER_CREATED_VERSION", { enumerable: true, get: function () { return inventory_events_2.PURCHASE_ORDER_CREATED_VERSION; } });
Object.defineProperty(exports, "GOODS_RECEIPT_CREATED_VERSION", { enumerable: true, get: function () { return inventory_events_2.GOODS_RECEIPT_CREATED_VERSION; } });
var inventory_events_3 = require("./inventory.events");
Object.defineProperty(exports, "isStockDeductedEvent", { enumerable: true, get: function () { return inventory_events_3.isStockDeductedEvent; } });
Object.defineProperty(exports, "isStockRestockedEvent", { enumerable: true, get: function () { return inventory_events_3.isStockRestockedEvent; } });
Object.defineProperty(exports, "isStockLowEvent", { enumerable: true, get: function () { return inventory_events_3.isStockLowEvent; } });
Object.defineProperty(exports, "isStockExpiredEvent", { enumerable: true, get: function () { return inventory_events_3.isStockExpiredEvent; } });
Object.defineProperty(exports, "isPurchaseOrderCreatedEvent", { enumerable: true, get: function () { return inventory_events_3.isPurchaseOrderCreatedEvent; } });
Object.defineProperty(exports, "isGoodsReceiptCreatedEvent", { enumerable: true, get: function () { return inventory_events_3.isGoodsReceiptCreatedEvent; } });
var inventory_events_4 = require("./inventory.events");
Object.defineProperty(exports, "createStockDeductedEvent", { enumerable: true, get: function () { return inventory_events_4.createStockDeductedEvent; } });
Object.defineProperty(exports, "createStockRestockedEvent", { enumerable: true, get: function () { return inventory_events_4.createStockRestockedEvent; } });
Object.defineProperty(exports, "createStockLowEvent", { enumerable: true, get: function () { return inventory_events_4.createStockLowEvent; } });
Object.defineProperty(exports, "createStockExpiredEvent", { enumerable: true, get: function () { return inventory_events_4.createStockExpiredEvent; } });
Object.defineProperty(exports, "createPurchaseOrderCreatedEvent", { enumerable: true, get: function () { return inventory_events_4.createPurchaseOrderCreatedEvent; } });
Object.defineProperty(exports, "createGoodsReceiptCreatedEvent", { enumerable: true, get: function () { return inventory_events_4.createGoodsReceiptCreatedEvent; } });
//# sourceMappingURL=index.js.map