import type { UUID, OrganizationId, ClinicId, ISODateString } from '@dentalos/shared-types';
import type { EventEnvelope } from '../envelope/event-envelope';
export declare const STOCK_DEDUCTED_EVENT: "dental.inventory.stock.deducted";
export declare const STOCK_RESTOCKED_EVENT: "dental.inventory.stock.restocked";
export declare const STOCK_LOW_EVENT: "dental.inventory.stock.low";
export declare const STOCK_EXPIRED_EVENT: "dental.inventory.stock.expired";
export declare const PURCHASE_ORDER_CREATED_EVENT: "dental.inventory.purchase-order.created";
export declare const GOODS_RECEIPT_CREATED_EVENT: "dental.inventory.goods-receipt.created";
export declare const STOCK_DEDUCTED_VERSION = 1;
export declare const STOCK_RESTOCKED_VERSION = 1;
export declare const STOCK_LOW_VERSION = 1;
export declare const STOCK_EXPIRED_VERSION = 1;
export declare const PURCHASE_ORDER_CREATED_VERSION = 1;
export declare const GOODS_RECEIPT_CREATED_VERSION = 1;
export type StockDeductionReason = 'PROCEDURE_CONSUMPTION' | 'ADJUSTMENT_NEGATIVE' | 'TRANSFER_OUT' | 'DISPOSAL' | 'LOST' | 'SAMPLE' | 'WASTAGE' | 'RETURN_TO_SUPPLIER' | 'OTHER';
export type StockRestockReason = 'PURCHASE_ORDER_RECEIVED' | 'TRANSFER_IN' | 'ADJUSTMENT_POSITIVE' | 'RETURN_FROM_PROCEDURE' | 'FOUND' | 'OTHER';
export type ExpiredStockAction = 'QUARANTINE' | 'DISPOSE' | 'RETURN' | 'EXTEND_EXPIRY' | 'USE_IMMEDIATELY';
export type PurchaseOrderUrgency = 'ROUTINE' | 'EXPEDITED' | 'URGENT' | 'EMERGENCY';
export interface GoodsReceiptItem {
    productId: UUID;
    productName: string;
    sku?: string;
    quantityReceived: number;
    unitOfMeasure: string;
    lotNumber: string;
    expirationDate?: ISODateString;
    unitCost?: number;
    lineTotalCost?: number;
    locationId?: UUID;
}
export interface StockDeductedPayload {
    productId: UUID;
    productName: string;
    sku: string;
    quantity: number;
    unitOfMeasure: string;
    lotNumber: string;
    expirationDate?: ISODateString;
    locationId: UUID;
    locationName?: string;
    procedureId?: UUID;
    procedureCode?: string;
    procedureName?: string;
    patientId?: UUID;
    patientName?: string;
    providerId: UUID;
    providerName?: string;
    reason: StockDeductionReason;
    notes?: string;
    costValue: number;
    currency?: string;
    timestamp: ISODateString;
    tenantId: string;
    organizationId: OrganizationId;
    clinicId: ClinicId;
    deductedBy?: UUID;
    deductedByName?: string;
    stockMovementId?: UUID;
    remainingQuantity?: number;
    triggeredLowStockAlert?: boolean;
    metadata?: Record<string, unknown>;
}
export type StockDeductedEvent = EventEnvelope<StockDeductedPayload>;
export declare function isStockDeductedEvent(event: EventEnvelope<unknown>): event is StockDeductedEvent;
export declare function createStockDeductedEvent(payload: StockDeductedPayload, metadata: EventEnvelope<unknown>['metadata'], tenantContext: EventEnvelope<unknown>['tenantContext']): StockDeductedEvent;
export interface StockRestockedPayload {
    productId: UUID;
    productName: string;
    sku?: string;
    quantity: number;
    unitOfMeasure: string;
    lotNumber: string;
    expirationDate?: ISODateString;
    locationId: UUID;
    locationName?: string;
    goodsReceiptId?: UUID;
    goodsReceiptNumber?: string;
    purchaseOrderId?: UUID;
    purchaseOrderNumber?: string;
    supplierId?: UUID;
    supplierName?: string;
    receivedBy: UUID;
    receivedByName?: string;
    reason?: StockRestockReason;
    notes?: string;
    costValue: number;
    unitCost?: number;
    currency?: string;
    timestamp: ISODateString;
    tenantId: string;
    organizationId: OrganizationId;
    clinicId: ClinicId;
    stockMovementId?: UUID;
    newTotalQuantity?: number;
    resolvedLowStockAlert?: boolean;
    qualityControlStatus?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'NOT_REQUIRED';
    qualityControlNotes?: string;
    metadata?: Record<string, unknown>;
}
export type StockRestockedEvent = EventEnvelope<StockRestockedPayload>;
export declare function isStockRestockedEvent(event: EventEnvelope<unknown>): event is StockRestockedEvent;
export declare function createStockRestockedEvent(payload: StockRestockedPayload, metadata: EventEnvelope<unknown>['metadata'], tenantContext: EventEnvelope<unknown>['tenantContext']): StockRestockedEvent;
export interface StockLowPayload {
    productId: UUID;
    productName: string;
    sku: string;
    currentQuantity: number;
    unitOfMeasure?: string;
    reorderPoint: number;
    reorderQuantity: number;
    locationId: UUID;
    locationName?: string;
    supplierId?: UUID;
    supplierName?: string;
    lastOrderDate?: ISODateString;
    averageConsumptionRate?: number;
    estimatedDaysUntilStockout?: number;
    autoReorderEnabled: boolean;
    triggeredPurchaseOrderId?: UUID;
    timestamp: ISODateString;
    tenantId: string;
    organizationId: OrganizationId;
    clinicId: ClinicId;
    severity?: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
    isCriticalProduct?: boolean;
    productCategory?: string;
    metadata?: Record<string, unknown>;
}
export type StockLowEvent = EventEnvelope<StockLowPayload>;
export declare function isStockLowEvent(event: EventEnvelope<unknown>): event is StockLowEvent;
export declare function createStockLowEvent(payload: StockLowPayload, metadata: EventEnvelope<unknown>['metadata'], tenantContext: EventEnvelope<unknown>['tenantContext']): StockLowEvent;
export interface StockExpiredPayload {
    productId: UUID;
    productName: string;
    sku?: string;
    lotNumber: string;
    quantity: number;
    unitOfMeasure?: string;
    expirationDate: ISODateString;
    locationId: UUID;
    locationName?: string;
    action: ExpiredStockAction;
    disposedBy?: UUID;
    disposedByName?: string;
    costValue?: number;
    currency?: string;
    notes?: string;
    timestamp: ISODateString;
    tenantId: string;
    organizationId: OrganizationId;
    clinicId: ClinicId;
    quarantineLocationId?: UUID;
    supplierId?: UUID;
    supplierName?: string;
    daysPastExpiration?: number;
    isAutomatedDetection?: boolean;
    productCategory?: string;
    metadata?: Record<string, unknown>;
}
export type StockExpiredEvent = EventEnvelope<StockExpiredPayload>;
export declare function isStockExpiredEvent(event: EventEnvelope<unknown>): event is StockExpiredEvent;
export declare function createStockExpiredEvent(payload: StockExpiredPayload, metadata: EventEnvelope<unknown>['metadata'], tenantContext: EventEnvelope<unknown>['tenantContext']): StockExpiredEvent;
export interface PurchaseOrderCreatedPayload {
    purchaseOrderId: UUID;
    orderNumber: string;
    supplierId: UUID;
    supplierName: string;
    supplierContact?: {
        email?: string;
        phone?: string;
        contactPerson?: string;
    };
    itemCount: number;
    totalAmount: number;
    currency?: string;
    expectedDeliveryDate?: ISODateString;
    createdBy: UUID;
    createdByName?: string;
    urgency: PurchaseOrderUrgency;
    deliveryLocationId?: UUID;
    deliveryLocationName?: string;
    status?: 'DRAFT' | 'PENDING_APPROVAL' | 'APPROVED' | 'SENT' | 'PARTIALLY_RECEIVED' | 'RECEIVED' | 'CANCELLED';
    approvalWorkflowId?: UUID;
    requiresApproval?: boolean;
    department?: string;
    triggeredByStockLowEventId?: UUID;
    notes?: string;
    timestamp: ISODateString;
    tenantId: string;
    organizationId: OrganizationId;
    clinicId: ClinicId;
    shippingMethod?: 'STANDARD' | 'EXPEDITED' | 'OVERNIGHT' | 'PICKUP';
    shippingCost?: number;
    taxAmount?: number;
    paymentTerms?: string;
    metadata?: Record<string, unknown>;
}
export type PurchaseOrderCreatedEvent = EventEnvelope<PurchaseOrderCreatedPayload>;
export declare function isPurchaseOrderCreatedEvent(event: EventEnvelope<unknown>): event is PurchaseOrderCreatedEvent;
export declare function createPurchaseOrderCreatedEvent(payload: PurchaseOrderCreatedPayload, metadata: EventEnvelope<unknown>['metadata'], tenantContext: EventEnvelope<unknown>['tenantContext']): PurchaseOrderCreatedEvent;
export interface GoodsReceiptCreatedPayload {
    goodsReceiptId: UUID;
    receiptNumber: string;
    purchaseOrderId?: UUID;
    purchaseOrderNumber?: string;
    supplierId: UUID;
    supplierName?: string;
    itemsReceived: GoodsReceiptItem[];
    totalItemsCount?: number;
    receivedBy: UUID;
    receivedByName?: string;
    deliveryLocationId?: UUID;
    deliveryLocationName?: string;
    deliveryDate?: ISODateString;
    notes?: string;
    qualityInspectionStatus?: 'PASSED' | 'FAILED' | 'PARTIAL' | 'NOT_REQUIRED';
    qualityInspectionNotes?: string;
    isDamaged?: boolean;
    damageDescription?: string;
    isComplete?: boolean;
    discrepancyNotes?: string;
    packingSlipNumber?: string;
    carrier?: string;
    trackingNumber?: string;
    totalValue?: number;
    currency?: string;
    timestamp: ISODateString;
    tenantId: string;
    organizationId: OrganizationId;
    clinicId: ClinicId;
    isMatchedToInvoice?: boolean;
    invoiceId?: UUID;
    metadata?: Record<string, unknown>;
}
export type GoodsReceiptCreatedEvent = EventEnvelope<GoodsReceiptCreatedPayload>;
export declare function isGoodsReceiptCreatedEvent(event: EventEnvelope<unknown>): event is GoodsReceiptCreatedEvent;
export declare function createGoodsReceiptCreatedEvent(payload: GoodsReceiptCreatedPayload, metadata: EventEnvelope<unknown>['metadata'], tenantContext: EventEnvelope<unknown>['tenantContext']): GoodsReceiptCreatedEvent;
