import { z } from 'zod';
import { UserRole, PermissionAction, ResourceType, UserStatus, AppointmentStatus, TreatmentStatus, Status, ApprovalStatus, PaymentStatus, Priority, Gender, MaritalStatus, ContactMethod, NotificationType, NotificationChannel, DocumentType, RecurrencePattern, DayOfWeek, CurrencyCode, LanguageCode, TimeZone, TenantType, TenantIsolationPolicy, EntityStatus } from '@dentalos/shared-types';
export declare const UUIDSchema: z.ZodString;
export declare const EmailSchema: z.ZodString;
export declare const PhoneNumberSchema: z.ZodString;
export declare const ISODateStringSchema: z.ZodString;
export declare const DateSchema: z.ZodEffects<z.ZodString, Date, string>;
export declare const DateOnlySchema: z.ZodEffects<z.ZodString, string, string>;
export declare const URLSchema: z.ZodString;
export declare const PositiveIntSchema: z.ZodNumber;
export declare const NonNegativeIntSchema: z.ZodNumber;
export declare const NonEmptyStringSchema: z.ZodString;
export declare const TrimmedStringSchema: z.ZodString;
export declare const SlugSchema: z.ZodString;
export declare const PasswordSchema: z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodString, string, string>, string, string>, string, string>, string, string>;
export declare const UserRoleSchema: z.ZodNativeEnum<typeof UserRole>;
export declare const PermissionActionSchema: z.ZodNativeEnum<typeof PermissionAction>;
export declare const ResourceTypeSchema: z.ZodNativeEnum<typeof ResourceType>;
export declare const UserStatusSchema: z.ZodNativeEnum<typeof UserStatus>;
export declare const AppointmentStatusSchema: z.ZodNativeEnum<typeof AppointmentStatus>;
export declare const TreatmentStatusSchema: z.ZodNativeEnum<typeof TreatmentStatus>;
export declare const StatusSchema: z.ZodNativeEnum<typeof Status>;
export declare const ApprovalStatusSchema: z.ZodNativeEnum<typeof ApprovalStatus>;
export declare const PaymentStatusSchema: z.ZodNativeEnum<typeof PaymentStatus>;
export declare const PrioritySchema: z.ZodNativeEnum<typeof Priority>;
export declare const GenderSchema: z.ZodNativeEnum<typeof Gender>;
export declare const MaritalStatusSchema: z.ZodNativeEnum<typeof MaritalStatus>;
export declare const ContactMethodSchema: z.ZodNativeEnum<typeof ContactMethod>;
export declare const NotificationTypeSchema: z.ZodNativeEnum<typeof NotificationType>;
export declare const NotificationChannelSchema: z.ZodNativeEnum<typeof NotificationChannel>;
export declare const DocumentTypeSchema: z.ZodNativeEnum<typeof DocumentType>;
export declare const RecurrencePatternSchema: z.ZodNativeEnum<typeof RecurrencePattern>;
export declare const DayOfWeekSchema: z.ZodNativeEnum<typeof DayOfWeek>;
export declare const CurrencyCodeSchema: z.ZodNativeEnum<typeof CurrencyCode>;
export declare const LanguageCodeSchema: z.ZodNativeEnum<typeof LanguageCode>;
export declare const TimeZoneSchema: z.ZodNativeEnum<typeof TimeZone>;
export declare const TenantTypeSchema: z.ZodNativeEnum<typeof TenantType>;
export declare const TenantIsolationPolicySchema: z.ZodNativeEnum<typeof TenantIsolationPolicy>;
export declare const EntityStatusSchema: z.ZodNativeEnum<typeof EntityStatus>;
export declare const PermissionSchema: z.ZodObject<{
    resource: z.ZodNativeEnum<typeof ResourceType>;
    action: z.ZodNativeEnum<typeof PermissionAction>;
    constraints: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
}, "strip", z.ZodTypeAny, {
    resource: ResourceType;
    action: PermissionAction;
    constraints?: Record<string, unknown> | undefined;
}, {
    resource: ResourceType;
    action: PermissionAction;
    constraints?: Record<string, unknown> | undefined;
}>;
export declare const SortOrderSchema: z.ZodEnum<["asc", "desc"]>;
export declare const MetadataSchema: z.ZodRecord<z.ZodString, z.ZodUnknown>;
