import { z } from 'zod';
import { CurrencyCode } from '@dentalos/shared-types';
export declare const MoneyAmountSchema: z.ZodEffects<z.ZodNumber, number, number>;
export declare const PositiveMoneyAmountSchema: z.ZodEffects<z.ZodNumber, number, number>;
export declare const NonNegativeMoneyAmountSchema: z.ZodEffects<z.ZodNumber, number, number>;
export declare const TaxRateSchema: z.ZodNumber;
export declare const InvoiceStatusSchema: z.ZodEnum<["DRAFT", "ISSUED", "PARTIALLY_PAID", "PAID", "OVERDUE", "CANCELLED", "REFUNDED", "PARTIALLY_REFUNDED"]>;
export declare const ItemTypeSchema: z.ZodEnum<["PROCEDURE", "PRODUCT", "SERVICE", "LAB_FEE", "ADJUSTMENT", "TAX", "OTHER"]>;
export declare const CreateInvoiceDtoSchema: z.ZodEffects<z.ZodEffects<z.ZodObject<{
    patientId: z.ZodString;
    providerId: z.ZodString;
    clinicId: z.ZodOptional<z.ZodString>;
    appointmentId: z.ZodOptional<z.ZodString>;
    treatmentPlanId: z.ZodOptional<z.ZodString>;
    invoiceNumber: z.ZodOptional<z.ZodString>;
    issueDate: z.ZodEffects<z.ZodString, string, string>;
    dueDate: z.ZodEffects<z.ZodString, string, string>;
    currency: z.ZodDefault<z.ZodNativeEnum<typeof CurrencyCode>>;
    notes: z.ZodOptional<z.ZodString>;
    internalNotes: z.ZodOptional<z.ZodString>;
    customerCUI: z.ZodOptional<z.ZodString>;
    customerName: z.ZodOptional<z.ZodString>;
    customerAddress: z.ZodOptional<z.ZodString>;
    paymentTerms: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    currency: CurrencyCode;
    dueDate: string;
    patientId: string;
    providerId: string;
    issueDate: string;
    clinicId?: string | undefined;
    invoiceNumber?: string | undefined;
    notes?: string | undefined;
    treatmentPlanId?: string | undefined;
    appointmentId?: string | undefined;
    internalNotes?: string | undefined;
    customerCUI?: string | undefined;
    customerName?: string | undefined;
    customerAddress?: string | undefined;
    paymentTerms?: string | undefined;
}, {
    dueDate: string;
    patientId: string;
    providerId: string;
    issueDate: string;
    clinicId?: string | undefined;
    currency?: CurrencyCode | undefined;
    invoiceNumber?: string | undefined;
    notes?: string | undefined;
    treatmentPlanId?: string | undefined;
    appointmentId?: string | undefined;
    internalNotes?: string | undefined;
    customerCUI?: string | undefined;
    customerName?: string | undefined;
    customerAddress?: string | undefined;
    paymentTerms?: string | undefined;
}>, {
    currency: CurrencyCode;
    dueDate: string;
    patientId: string;
    providerId: string;
    issueDate: string;
    clinicId?: string | undefined;
    invoiceNumber?: string | undefined;
    notes?: string | undefined;
    treatmentPlanId?: string | undefined;
    appointmentId?: string | undefined;
    internalNotes?: string | undefined;
    customerCUI?: string | undefined;
    customerName?: string | undefined;
    customerAddress?: string | undefined;
    paymentTerms?: string | undefined;
}, {
    dueDate: string;
    patientId: string;
    providerId: string;
    issueDate: string;
    clinicId?: string | undefined;
    currency?: CurrencyCode | undefined;
    invoiceNumber?: string | undefined;
    notes?: string | undefined;
    treatmentPlanId?: string | undefined;
    appointmentId?: string | undefined;
    internalNotes?: string | undefined;
    customerCUI?: string | undefined;
    customerName?: string | undefined;
    customerAddress?: string | undefined;
    paymentTerms?: string | undefined;
}>, {
    currency: CurrencyCode;
    dueDate: string;
    patientId: string;
    providerId: string;
    issueDate: string;
    clinicId?: string | undefined;
    invoiceNumber?: string | undefined;
    notes?: string | undefined;
    treatmentPlanId?: string | undefined;
    appointmentId?: string | undefined;
    internalNotes?: string | undefined;
    customerCUI?: string | undefined;
    customerName?: string | undefined;
    customerAddress?: string | undefined;
    paymentTerms?: string | undefined;
}, {
    dueDate: string;
    patientId: string;
    providerId: string;
    issueDate: string;
    clinicId?: string | undefined;
    currency?: CurrencyCode | undefined;
    invoiceNumber?: string | undefined;
    notes?: string | undefined;
    treatmentPlanId?: string | undefined;
    appointmentId?: string | undefined;
    internalNotes?: string | undefined;
    customerCUI?: string | undefined;
    customerName?: string | undefined;
    customerAddress?: string | undefined;
    paymentTerms?: string | undefined;
}>;
export declare const UpdateInvoiceStatusDtoSchema: z.ZodObject<{
    status: z.ZodEnum<["DRAFT", "ISSUED", "PARTIALLY_PAID", "PAID", "OVERDUE", "CANCELLED", "REFUNDED", "PARTIALLY_REFUNDED"]>;
    reason: z.ZodOptional<z.ZodString>;
    updatedBy: z.ZodString;
}, "strip", z.ZodTypeAny, {
    status: "DRAFT" | "CANCELLED" | "PARTIALLY_PAID" | "PAID" | "OVERDUE" | "REFUNDED" | "ISSUED" | "PARTIALLY_REFUNDED";
    updatedBy: string;
    reason?: string | undefined;
}, {
    status: "DRAFT" | "CANCELLED" | "PARTIALLY_PAID" | "PAID" | "OVERDUE" | "REFUNDED" | "ISSUED" | "PARTIALLY_REFUNDED";
    updatedBy: string;
    reason?: string | undefined;
}>;
export declare const QueryInvoicesDtoSchema: z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodObject<{
    patientId: z.ZodOptional<z.ZodString>;
    providerId: z.ZodOptional<z.ZodString>;
    clinicId: z.ZodOptional<z.ZodString>;
    appointmentId: z.ZodOptional<z.ZodString>;
    treatmentPlanId: z.ZodOptional<z.ZodString>;
    invoiceNumber: z.ZodOptional<z.ZodString>;
    status: z.ZodOptional<z.ZodArray<z.ZodEnum<["DRAFT", "ISSUED", "PARTIALLY_PAID", "PAID", "OVERDUE", "CANCELLED", "REFUNDED", "PARTIALLY_REFUNDED"]>, "many">>;
    issueDateFrom: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    issueDateTo: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    dueDateFrom: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    dueDateTo: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    minAmount: z.ZodOptional<z.ZodEffects<z.ZodNumber, number, number>>;
    maxAmount: z.ZodOptional<z.ZodEffects<z.ZodNumber, number, number>>;
    currency: z.ZodOptional<z.ZodNativeEnum<typeof CurrencyCode>>;
    searchTerm: z.ZodOptional<z.ZodString>;
    page: z.ZodDefault<z.ZodNumber>;
    limit: z.ZodDefault<z.ZodNumber>;
    sortBy: z.ZodDefault<z.ZodEnum<["invoiceNumber", "issueDate", "dueDate", "totalAmount", "status", "patientName", "createdAt"]>>;
    sortOrder: z.ZodDefault<z.ZodEnum<["asc", "desc"]>>;
}, "strip", z.ZodTypeAny, {
    limit: number;
    page: number;
    sortBy: "status" | "createdAt" | "totalAmount" | "invoiceNumber" | "dueDate" | "issueDate" | "patientName";
    sortOrder: "asc" | "desc";
    status?: ("DRAFT" | "CANCELLED" | "PARTIALLY_PAID" | "PAID" | "OVERDUE" | "REFUNDED" | "ISSUED" | "PARTIALLY_REFUNDED")[] | undefined;
    clinicId?: string | undefined;
    currency?: CurrencyCode | undefined;
    invoiceNumber?: string | undefined;
    patientId?: string | undefined;
    providerId?: string | undefined;
    treatmentPlanId?: string | undefined;
    appointmentId?: string | undefined;
    minAmount?: number | undefined;
    maxAmount?: number | undefined;
    searchTerm?: string | undefined;
    issueDateFrom?: string | undefined;
    issueDateTo?: string | undefined;
    dueDateFrom?: string | undefined;
    dueDateTo?: string | undefined;
}, {
    status?: ("DRAFT" | "CANCELLED" | "PARTIALLY_PAID" | "PAID" | "OVERDUE" | "REFUNDED" | "ISSUED" | "PARTIALLY_REFUNDED")[] | undefined;
    clinicId?: string | undefined;
    limit?: number | undefined;
    currency?: CurrencyCode | undefined;
    page?: number | undefined;
    sortBy?: "status" | "createdAt" | "totalAmount" | "invoiceNumber" | "dueDate" | "issueDate" | "patientName" | undefined;
    sortOrder?: "asc" | "desc" | undefined;
    invoiceNumber?: string | undefined;
    patientId?: string | undefined;
    providerId?: string | undefined;
    treatmentPlanId?: string | undefined;
    appointmentId?: string | undefined;
    minAmount?: number | undefined;
    maxAmount?: number | undefined;
    searchTerm?: string | undefined;
    issueDateFrom?: string | undefined;
    issueDateTo?: string | undefined;
    dueDateFrom?: string | undefined;
    dueDateTo?: string | undefined;
}>, {
    limit: number;
    page: number;
    sortBy: "status" | "createdAt" | "totalAmount" | "invoiceNumber" | "dueDate" | "issueDate" | "patientName";
    sortOrder: "asc" | "desc";
    status?: ("DRAFT" | "CANCELLED" | "PARTIALLY_PAID" | "PAID" | "OVERDUE" | "REFUNDED" | "ISSUED" | "PARTIALLY_REFUNDED")[] | undefined;
    clinicId?: string | undefined;
    currency?: CurrencyCode | undefined;
    invoiceNumber?: string | undefined;
    patientId?: string | undefined;
    providerId?: string | undefined;
    treatmentPlanId?: string | undefined;
    appointmentId?: string | undefined;
    minAmount?: number | undefined;
    maxAmount?: number | undefined;
    searchTerm?: string | undefined;
    issueDateFrom?: string | undefined;
    issueDateTo?: string | undefined;
    dueDateFrom?: string | undefined;
    dueDateTo?: string | undefined;
}, {
    status?: ("DRAFT" | "CANCELLED" | "PARTIALLY_PAID" | "PAID" | "OVERDUE" | "REFUNDED" | "ISSUED" | "PARTIALLY_REFUNDED")[] | undefined;
    clinicId?: string | undefined;
    limit?: number | undefined;
    currency?: CurrencyCode | undefined;
    page?: number | undefined;
    sortBy?: "status" | "createdAt" | "totalAmount" | "invoiceNumber" | "dueDate" | "issueDate" | "patientName" | undefined;
    sortOrder?: "asc" | "desc" | undefined;
    invoiceNumber?: string | undefined;
    patientId?: string | undefined;
    providerId?: string | undefined;
    treatmentPlanId?: string | undefined;
    appointmentId?: string | undefined;
    minAmount?: number | undefined;
    maxAmount?: number | undefined;
    searchTerm?: string | undefined;
    issueDateFrom?: string | undefined;
    issueDateTo?: string | undefined;
    dueDateFrom?: string | undefined;
    dueDateTo?: string | undefined;
}>, {
    limit: number;
    page: number;
    sortBy: "status" | "createdAt" | "totalAmount" | "invoiceNumber" | "dueDate" | "issueDate" | "patientName";
    sortOrder: "asc" | "desc";
    status?: ("DRAFT" | "CANCELLED" | "PARTIALLY_PAID" | "PAID" | "OVERDUE" | "REFUNDED" | "ISSUED" | "PARTIALLY_REFUNDED")[] | undefined;
    clinicId?: string | undefined;
    currency?: CurrencyCode | undefined;
    invoiceNumber?: string | undefined;
    patientId?: string | undefined;
    providerId?: string | undefined;
    treatmentPlanId?: string | undefined;
    appointmentId?: string | undefined;
    minAmount?: number | undefined;
    maxAmount?: number | undefined;
    searchTerm?: string | undefined;
    issueDateFrom?: string | undefined;
    issueDateTo?: string | undefined;
    dueDateFrom?: string | undefined;
    dueDateTo?: string | undefined;
}, {
    status?: ("DRAFT" | "CANCELLED" | "PARTIALLY_PAID" | "PAID" | "OVERDUE" | "REFUNDED" | "ISSUED" | "PARTIALLY_REFUNDED")[] | undefined;
    clinicId?: string | undefined;
    limit?: number | undefined;
    currency?: CurrencyCode | undefined;
    page?: number | undefined;
    sortBy?: "status" | "createdAt" | "totalAmount" | "invoiceNumber" | "dueDate" | "issueDate" | "patientName" | undefined;
    sortOrder?: "asc" | "desc" | undefined;
    invoiceNumber?: string | undefined;
    patientId?: string | undefined;
    providerId?: string | undefined;
    treatmentPlanId?: string | undefined;
    appointmentId?: string | undefined;
    minAmount?: number | undefined;
    maxAmount?: number | undefined;
    searchTerm?: string | undefined;
    issueDateFrom?: string | undefined;
    issueDateTo?: string | undefined;
    dueDateFrom?: string | undefined;
    dueDateTo?: string | undefined;
}>, {
    limit: number;
    page: number;
    sortBy: "status" | "createdAt" | "totalAmount" | "invoiceNumber" | "dueDate" | "issueDate" | "patientName";
    sortOrder: "asc" | "desc";
    status?: ("DRAFT" | "CANCELLED" | "PARTIALLY_PAID" | "PAID" | "OVERDUE" | "REFUNDED" | "ISSUED" | "PARTIALLY_REFUNDED")[] | undefined;
    clinicId?: string | undefined;
    currency?: CurrencyCode | undefined;
    invoiceNumber?: string | undefined;
    patientId?: string | undefined;
    providerId?: string | undefined;
    treatmentPlanId?: string | undefined;
    appointmentId?: string | undefined;
    minAmount?: number | undefined;
    maxAmount?: number | undefined;
    searchTerm?: string | undefined;
    issueDateFrom?: string | undefined;
    issueDateTo?: string | undefined;
    dueDateFrom?: string | undefined;
    dueDateTo?: string | undefined;
}, {
    status?: ("DRAFT" | "CANCELLED" | "PARTIALLY_PAID" | "PAID" | "OVERDUE" | "REFUNDED" | "ISSUED" | "PARTIALLY_REFUNDED")[] | undefined;
    clinicId?: string | undefined;
    limit?: number | undefined;
    currency?: CurrencyCode | undefined;
    page?: number | undefined;
    sortBy?: "status" | "createdAt" | "totalAmount" | "invoiceNumber" | "dueDate" | "issueDate" | "patientName" | undefined;
    sortOrder?: "asc" | "desc" | undefined;
    invoiceNumber?: string | undefined;
    patientId?: string | undefined;
    providerId?: string | undefined;
    treatmentPlanId?: string | undefined;
    appointmentId?: string | undefined;
    minAmount?: number | undefined;
    maxAmount?: number | undefined;
    searchTerm?: string | undefined;
    issueDateFrom?: string | undefined;
    issueDateTo?: string | undefined;
    dueDateFrom?: string | undefined;
    dueDateTo?: string | undefined;
}>;
export declare const AddInvoiceItemDtoSchema: z.ZodObject<{
    invoiceId: z.ZodString;
    itemType: z.ZodEnum<["PROCEDURE", "PRODUCT", "SERVICE", "LAB_FEE", "ADJUSTMENT", "TAX", "OTHER"]>;
    referenceId: z.ZodOptional<z.ZodString>;
    code: z.ZodString;
    description: z.ZodString;
    quantity: z.ZodNumber;
    unitPrice: z.ZodEffects<z.ZodNumber, number, number>;
    taxRate: z.ZodDefault<z.ZodNumber>;
    discount: z.ZodDefault<z.ZodEffects<z.ZodNumber, number, number>>;
    notes: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    code: string;
    description: string;
    quantity: number;
    unitPrice: number;
    invoiceId: string;
    taxRate: number;
    itemType: "OTHER" | "SERVICE" | "ADJUSTMENT" | "PROCEDURE" | "PRODUCT" | "LAB_FEE" | "TAX";
    discount: number;
    notes?: string | undefined;
    referenceId?: string | undefined;
}, {
    code: string;
    description: string;
    quantity: number;
    unitPrice: number;
    invoiceId: string;
    itemType: "OTHER" | "SERVICE" | "ADJUSTMENT" | "PROCEDURE" | "PRODUCT" | "LAB_FEE" | "TAX";
    notes?: string | undefined;
    taxRate?: number | undefined;
    referenceId?: string | undefined;
    discount?: number | undefined;
}>;
export declare const UpdateInvoiceItemDtoSchema: z.ZodObject<{
    itemType: z.ZodOptional<z.ZodEnum<["PROCEDURE", "PRODUCT", "SERVICE", "LAB_FEE", "ADJUSTMENT", "TAX", "OTHER"]>>;
    code: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    quantity: z.ZodOptional<z.ZodNumber>;
    unitPrice: z.ZodOptional<z.ZodEffects<z.ZodNumber, number, number>>;
    taxRate: z.ZodOptional<z.ZodNumber>;
    discount: z.ZodOptional<z.ZodEffects<z.ZodNumber, number, number>>;
    notes: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    code?: string | undefined;
    description?: string | undefined;
    quantity?: number | undefined;
    unitPrice?: number | undefined;
    notes?: string | undefined;
    taxRate?: number | undefined;
    itemType?: "OTHER" | "SERVICE" | "ADJUSTMENT" | "PROCEDURE" | "PRODUCT" | "LAB_FEE" | "TAX" | undefined;
    discount?: number | undefined;
}, {
    code?: string | undefined;
    description?: string | undefined;
    quantity?: number | undefined;
    unitPrice?: number | undefined;
    notes?: string | undefined;
    taxRate?: number | undefined;
    itemType?: "OTHER" | "SERVICE" | "ADJUSTMENT" | "PROCEDURE" | "PRODUCT" | "LAB_FEE" | "TAX" | undefined;
    discount?: number | undefined;
}>;
export declare const PaymentMethodSchema: z.ZodEnum<["CASH", "CARD", "BANK_TRANSFER", "CHECK", "INSURANCE", "ONLINE", "MOBILE_PAYMENT", "VOUCHER", "OTHER"]>;
export declare const RecordPaymentDtoSchema: z.ZodEffects<z.ZodEffects<z.ZodObject<{
    invoiceId: z.ZodString;
    amount: z.ZodEffects<z.ZodNumber, number, number>;
    paymentMethod: z.ZodEnum<["CASH", "CARD", "BANK_TRANSFER", "CHECK", "INSURANCE", "ONLINE", "MOBILE_PAYMENT", "VOUCHER", "OTHER"]>;
    paymentDate: z.ZodEffects<z.ZodString, string, string>;
    transactionId: z.ZodOptional<z.ZodString>;
    referenceNumber: z.ZodOptional<z.ZodString>;
    notes: z.ZodOptional<z.ZodString>;
    receivedBy: z.ZodString;
    currency: z.ZodOptional<z.ZodNativeEnum<typeof CurrencyCode>>;
    exchangeRate: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    paymentMethod: "OTHER" | "INSURANCE" | "CARD" | "BANK_TRANSFER" | "CASH" | "CHECK" | "ONLINE" | "MOBILE_PAYMENT" | "VOUCHER";
    amount: number;
    invoiceId: string;
    paymentDate: string;
    receivedBy: string;
    currency?: CurrencyCode | undefined;
    notes?: string | undefined;
    transactionId?: string | undefined;
    referenceNumber?: string | undefined;
    exchangeRate?: number | undefined;
}, {
    paymentMethod: "OTHER" | "INSURANCE" | "CARD" | "BANK_TRANSFER" | "CASH" | "CHECK" | "ONLINE" | "MOBILE_PAYMENT" | "VOUCHER";
    amount: number;
    invoiceId: string;
    paymentDate: string;
    receivedBy: string;
    currency?: CurrencyCode | undefined;
    notes?: string | undefined;
    transactionId?: string | undefined;
    referenceNumber?: string | undefined;
    exchangeRate?: number | undefined;
}>, {
    paymentMethod: "OTHER" | "INSURANCE" | "CARD" | "BANK_TRANSFER" | "CASH" | "CHECK" | "ONLINE" | "MOBILE_PAYMENT" | "VOUCHER";
    amount: number;
    invoiceId: string;
    paymentDate: string;
    receivedBy: string;
    currency?: CurrencyCode | undefined;
    notes?: string | undefined;
    transactionId?: string | undefined;
    referenceNumber?: string | undefined;
    exchangeRate?: number | undefined;
}, {
    paymentMethod: "OTHER" | "INSURANCE" | "CARD" | "BANK_TRANSFER" | "CASH" | "CHECK" | "ONLINE" | "MOBILE_PAYMENT" | "VOUCHER";
    amount: number;
    invoiceId: string;
    paymentDate: string;
    receivedBy: string;
    currency?: CurrencyCode | undefined;
    notes?: string | undefined;
    transactionId?: string | undefined;
    referenceNumber?: string | undefined;
    exchangeRate?: number | undefined;
}>, {
    paymentMethod: "OTHER" | "INSURANCE" | "CARD" | "BANK_TRANSFER" | "CASH" | "CHECK" | "ONLINE" | "MOBILE_PAYMENT" | "VOUCHER";
    amount: number;
    invoiceId: string;
    paymentDate: string;
    receivedBy: string;
    currency?: CurrencyCode | undefined;
    notes?: string | undefined;
    transactionId?: string | undefined;
    referenceNumber?: string | undefined;
    exchangeRate?: number | undefined;
}, {
    paymentMethod: "OTHER" | "INSURANCE" | "CARD" | "BANK_TRANSFER" | "CASH" | "CHECK" | "ONLINE" | "MOBILE_PAYMENT" | "VOUCHER";
    amount: number;
    invoiceId: string;
    paymentDate: string;
    receivedBy: string;
    currency?: CurrencyCode | undefined;
    notes?: string | undefined;
    transactionId?: string | undefined;
    referenceNumber?: string | undefined;
    exchangeRate?: number | undefined;
}>;
export declare const SplitPaymentItemSchema: z.ZodObject<{
    paymentMethod: z.ZodEnum<["CASH", "CARD", "BANK_TRANSFER", "CHECK", "INSURANCE", "ONLINE", "MOBILE_PAYMENT", "VOUCHER", "OTHER"]>;
    amount: z.ZodEffects<z.ZodNumber, number, number>;
    transactionId: z.ZodOptional<z.ZodString>;
    referenceNumber: z.ZodOptional<z.ZodString>;
    notes: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    paymentMethod: "OTHER" | "INSURANCE" | "CARD" | "BANK_TRANSFER" | "CASH" | "CHECK" | "ONLINE" | "MOBILE_PAYMENT" | "VOUCHER";
    amount: number;
    notes?: string | undefined;
    transactionId?: string | undefined;
    referenceNumber?: string | undefined;
}, {
    paymentMethod: "OTHER" | "INSURANCE" | "CARD" | "BANK_TRANSFER" | "CASH" | "CHECK" | "ONLINE" | "MOBILE_PAYMENT" | "VOUCHER";
    amount: number;
    notes?: string | undefined;
    transactionId?: string | undefined;
    referenceNumber?: string | undefined;
}>;
export declare const RecordSplitPaymentDtoSchema: z.ZodEffects<z.ZodEffects<z.ZodObject<{
    invoiceId: z.ZodString;
    splitPayments: z.ZodArray<z.ZodObject<{
        paymentMethod: z.ZodEnum<["CASH", "CARD", "BANK_TRANSFER", "CHECK", "INSURANCE", "ONLINE", "MOBILE_PAYMENT", "VOUCHER", "OTHER"]>;
        amount: z.ZodEffects<z.ZodNumber, number, number>;
        transactionId: z.ZodOptional<z.ZodString>;
        referenceNumber: z.ZodOptional<z.ZodString>;
        notes: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        paymentMethod: "OTHER" | "INSURANCE" | "CARD" | "BANK_TRANSFER" | "CASH" | "CHECK" | "ONLINE" | "MOBILE_PAYMENT" | "VOUCHER";
        amount: number;
        notes?: string | undefined;
        transactionId?: string | undefined;
        referenceNumber?: string | undefined;
    }, {
        paymentMethod: "OTHER" | "INSURANCE" | "CARD" | "BANK_TRANSFER" | "CASH" | "CHECK" | "ONLINE" | "MOBILE_PAYMENT" | "VOUCHER";
        amount: number;
        notes?: string | undefined;
        transactionId?: string | undefined;
        referenceNumber?: string | undefined;
    }>, "many">;
    totalAmount: z.ZodEffects<z.ZodNumber, number, number>;
    paymentDate: z.ZodEffects<z.ZodString, string, string>;
    notes: z.ZodOptional<z.ZodString>;
    receivedBy: z.ZodString;
}, "strip", z.ZodTypeAny, {
    totalAmount: number;
    invoiceId: string;
    paymentDate: string;
    receivedBy: string;
    splitPayments: {
        paymentMethod: "OTHER" | "INSURANCE" | "CARD" | "BANK_TRANSFER" | "CASH" | "CHECK" | "ONLINE" | "MOBILE_PAYMENT" | "VOUCHER";
        amount: number;
        notes?: string | undefined;
        transactionId?: string | undefined;
        referenceNumber?: string | undefined;
    }[];
    notes?: string | undefined;
}, {
    totalAmount: number;
    invoiceId: string;
    paymentDate: string;
    receivedBy: string;
    splitPayments: {
        paymentMethod: "OTHER" | "INSURANCE" | "CARD" | "BANK_TRANSFER" | "CASH" | "CHECK" | "ONLINE" | "MOBILE_PAYMENT" | "VOUCHER";
        amount: number;
        notes?: string | undefined;
        transactionId?: string | undefined;
        referenceNumber?: string | undefined;
    }[];
    notes?: string | undefined;
}>, {
    totalAmount: number;
    invoiceId: string;
    paymentDate: string;
    receivedBy: string;
    splitPayments: {
        paymentMethod: "OTHER" | "INSURANCE" | "CARD" | "BANK_TRANSFER" | "CASH" | "CHECK" | "ONLINE" | "MOBILE_PAYMENT" | "VOUCHER";
        amount: number;
        notes?: string | undefined;
        transactionId?: string | undefined;
        referenceNumber?: string | undefined;
    }[];
    notes?: string | undefined;
}, {
    totalAmount: number;
    invoiceId: string;
    paymentDate: string;
    receivedBy: string;
    splitPayments: {
        paymentMethod: "OTHER" | "INSURANCE" | "CARD" | "BANK_TRANSFER" | "CASH" | "CHECK" | "ONLINE" | "MOBILE_PAYMENT" | "VOUCHER";
        amount: number;
        notes?: string | undefined;
        transactionId?: string | undefined;
        referenceNumber?: string | undefined;
    }[];
    notes?: string | undefined;
}>, {
    totalAmount: number;
    invoiceId: string;
    paymentDate: string;
    receivedBy: string;
    splitPayments: {
        paymentMethod: "OTHER" | "INSURANCE" | "CARD" | "BANK_TRANSFER" | "CASH" | "CHECK" | "ONLINE" | "MOBILE_PAYMENT" | "VOUCHER";
        amount: number;
        notes?: string | undefined;
        transactionId?: string | undefined;
        referenceNumber?: string | undefined;
    }[];
    notes?: string | undefined;
}, {
    totalAmount: number;
    invoiceId: string;
    paymentDate: string;
    receivedBy: string;
    splitPayments: {
        paymentMethod: "OTHER" | "INSURANCE" | "CARD" | "BANK_TRANSFER" | "CASH" | "CHECK" | "ONLINE" | "MOBILE_PAYMENT" | "VOUCHER";
        amount: number;
        notes?: string | undefined;
        transactionId?: string | undefined;
        referenceNumber?: string | undefined;
    }[];
    notes?: string | undefined;
}>;
export declare const RefundPaymentDtoSchema: z.ZodObject<{
    paymentId: z.ZodString;
    refundAmount: z.ZodEffects<z.ZodNumber, number, number>;
    reason: z.ZodString;
    refundDate: z.ZodEffects<z.ZodString, string, string>;
    refundMethod: z.ZodOptional<z.ZodEnum<["CASH", "CARD", "BANK_TRANSFER", "CHECK", "INSURANCE", "ONLINE", "MOBILE_PAYMENT", "VOUCHER", "OTHER"]>>;
    transactionId: z.ZodOptional<z.ZodString>;
    notes: z.ZodOptional<z.ZodString>;
    processedBy: z.ZodString;
}, "strip", z.ZodTypeAny, {
    reason: string;
    paymentId: string;
    refundAmount: number;
    refundDate: string;
    processedBy: string;
    notes?: string | undefined;
    transactionId?: string | undefined;
    refundMethod?: "OTHER" | "INSURANCE" | "CARD" | "BANK_TRANSFER" | "CASH" | "CHECK" | "ONLINE" | "MOBILE_PAYMENT" | "VOUCHER" | undefined;
}, {
    reason: string;
    paymentId: string;
    refundAmount: number;
    refundDate: string;
    processedBy: string;
    notes?: string | undefined;
    transactionId?: string | undefined;
    refundMethod?: "OTHER" | "INSURANCE" | "CARD" | "BANK_TRANSFER" | "CASH" | "CHECK" | "ONLINE" | "MOBILE_PAYMENT" | "VOUCHER" | undefined;
}>;
export declare const ClaimStatusSchema: z.ZodEnum<["DRAFT", "SUBMITTED", "PENDING_REVIEW", "APPROVED", "PARTIALLY_APPROVED", "DENIED", "PAID", "APPEALED", "CANCELLED"]>;
export declare const CreateInsuranceClaimDtoSchema: z.ZodObject<{
    invoiceId: z.ZodString;
    patientId: z.ZodString;
    insuranceProviderId: z.ZodString;
    policyNumber: z.ZodString;
    claimedAmount: z.ZodEffects<z.ZodNumber, number, number>;
    procedureCodes: z.ZodArray<z.ZodString, "many">;
    diagnosisCodes: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    treatmentDate: z.ZodEffects<z.ZodString, string, string>;
    submissionDate: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    notes: z.ZodOptional<z.ZodString>;
    attachments: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    submittedBy: z.ZodString;
}, "strip", z.ZodTypeAny, {
    patientId: string;
    invoiceId: string;
    insuranceProviderId: string;
    policyNumber: string;
    claimedAmount: number;
    procedureCodes: string[];
    treatmentDate: string;
    submittedBy: string;
    notes?: string | undefined;
    attachments?: string[] | undefined;
    diagnosisCodes?: string[] | undefined;
    submissionDate?: string | undefined;
}, {
    patientId: string;
    invoiceId: string;
    insuranceProviderId: string;
    policyNumber: string;
    claimedAmount: number;
    procedureCodes: string[];
    treatmentDate: string;
    submittedBy: string;
    notes?: string | undefined;
    attachments?: string[] | undefined;
    diagnosisCodes?: string[] | undefined;
    submissionDate?: string | undefined;
}>;
export declare const UpdateClaimStatusDtoSchema: z.ZodEffects<z.ZodEffects<z.ZodObject<{
    status: z.ZodEnum<["DRAFT", "SUBMITTED", "PENDING_REVIEW", "APPROVED", "PARTIALLY_APPROVED", "DENIED", "PAID", "APPEALED", "CANCELLED"]>;
    approvedAmount: z.ZodOptional<z.ZodEffects<z.ZodNumber, number, number>>;
    denialReason: z.ZodOptional<z.ZodString>;
    insurerReferenceNumber: z.ZodOptional<z.ZodString>;
    responseDate: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    notes: z.ZodOptional<z.ZodString>;
    updatedBy: z.ZodString;
}, "strip", z.ZodTypeAny, {
    status: "DRAFT" | "APPROVED" | "CANCELLED" | "PAID" | "SUBMITTED" | "PENDING_REVIEW" | "PARTIALLY_APPROVED" | "DENIED" | "APPEALED";
    updatedBy: string;
    notes?: string | undefined;
    approvedAmount?: number | undefined;
    denialReason?: string | undefined;
    insurerReferenceNumber?: string | undefined;
    responseDate?: string | undefined;
}, {
    status: "DRAFT" | "APPROVED" | "CANCELLED" | "PAID" | "SUBMITTED" | "PENDING_REVIEW" | "PARTIALLY_APPROVED" | "DENIED" | "APPEALED";
    updatedBy: string;
    notes?: string | undefined;
    approvedAmount?: number | undefined;
    denialReason?: string | undefined;
    insurerReferenceNumber?: string | undefined;
    responseDate?: string | undefined;
}>, {
    status: "DRAFT" | "APPROVED" | "CANCELLED" | "PAID" | "SUBMITTED" | "PENDING_REVIEW" | "PARTIALLY_APPROVED" | "DENIED" | "APPEALED";
    updatedBy: string;
    notes?: string | undefined;
    approvedAmount?: number | undefined;
    denialReason?: string | undefined;
    insurerReferenceNumber?: string | undefined;
    responseDate?: string | undefined;
}, {
    status: "DRAFT" | "APPROVED" | "CANCELLED" | "PAID" | "SUBMITTED" | "PENDING_REVIEW" | "PARTIALLY_APPROVED" | "DENIED" | "APPEALED";
    updatedBy: string;
    notes?: string | undefined;
    approvedAmount?: number | undefined;
    denialReason?: string | undefined;
    insurerReferenceNumber?: string | undefined;
    responseDate?: string | undefined;
}>, {
    status: "DRAFT" | "APPROVED" | "CANCELLED" | "PAID" | "SUBMITTED" | "PENDING_REVIEW" | "PARTIALLY_APPROVED" | "DENIED" | "APPEALED";
    updatedBy: string;
    notes?: string | undefined;
    approvedAmount?: number | undefined;
    denialReason?: string | undefined;
    insurerReferenceNumber?: string | undefined;
    responseDate?: string | undefined;
}, {
    status: "DRAFT" | "APPROVED" | "CANCELLED" | "PAID" | "SUBMITTED" | "PENDING_REVIEW" | "PARTIALLY_APPROVED" | "DENIED" | "APPEALED";
    updatedBy: string;
    notes?: string | undefined;
    approvedAmount?: number | undefined;
    denialReason?: string | undefined;
    insurerReferenceNumber?: string | undefined;
    responseDate?: string | undefined;
}>;
export declare const RuleTypeSchema: z.ZodEnum<["PERCENTAGE_DISCOUNT", "FIXED_DISCOUNT", "FIXED_PRICE", "PERCENTAGE_MARKUP", "FIXED_MARKUP", "TIERED_PRICING", "BUNDLE_DISCOUNT"]>;
export declare const CreatePriceRuleDtoSchema: z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodEffects<z.ZodObject<{
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    ruleType: z.ZodEnum<["PERCENTAGE_DISCOUNT", "FIXED_DISCOUNT", "FIXED_PRICE", "PERCENTAGE_MARKUP", "FIXED_MARKUP", "TIERED_PRICING", "BUNDLE_DISCOUNT"]>;
    applicableTo: z.ZodEnum<["PROCEDURE", "PRODUCT", "SERVICE", "CATEGORY", "ALL"]>;
    targetIds: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    value: z.ZodNumber;
    validFrom: z.ZodEffects<z.ZodString, string, string>;
    validTo: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    priority: z.ZodDefault<z.ZodNumber>;
    isActive: z.ZodDefault<z.ZodBoolean>;
    minQuantity: z.ZodOptional<z.ZodNumber>;
    maxQuantity: z.ZodOptional<z.ZodNumber>;
    requiresInsurance: z.ZodDefault<z.ZodBoolean>;
    requiresCouponCode: z.ZodDefault<z.ZodBoolean>;
    couponCode: z.ZodOptional<z.ZodString>;
    clinicIds: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    patientCategories: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    createdBy: z.ZodString;
}, "strip", z.ZodTypeAny, {
    value: number;
    name: string;
    ruleType: "PERCENTAGE_DISCOUNT" | "FIXED_DISCOUNT" | "FIXED_PRICE" | "PERCENTAGE_MARKUP" | "FIXED_MARKUP" | "TIERED_PRICING" | "BUNDLE_DISCOUNT";
    priority: number;
    isActive: boolean;
    applicableTo: "SERVICE" | "PROCEDURE" | "PRODUCT" | "CATEGORY" | "ALL";
    validFrom: string;
    requiresInsurance: boolean;
    requiresCouponCode: boolean;
    createdBy: string;
    description?: string | undefined;
    clinicIds?: string[] | undefined;
    targetIds?: string[] | undefined;
    validTo?: string | undefined;
    minQuantity?: number | undefined;
    maxQuantity?: number | undefined;
    couponCode?: string | undefined;
    patientCategories?: string[] | undefined;
}, {
    value: number;
    name: string;
    ruleType: "PERCENTAGE_DISCOUNT" | "FIXED_DISCOUNT" | "FIXED_PRICE" | "PERCENTAGE_MARKUP" | "FIXED_MARKUP" | "TIERED_PRICING" | "BUNDLE_DISCOUNT";
    applicableTo: "SERVICE" | "PROCEDURE" | "PRODUCT" | "CATEGORY" | "ALL";
    validFrom: string;
    createdBy: string;
    description?: string | undefined;
    priority?: number | undefined;
    clinicIds?: string[] | undefined;
    isActive?: boolean | undefined;
    targetIds?: string[] | undefined;
    validTo?: string | undefined;
    minQuantity?: number | undefined;
    maxQuantity?: number | undefined;
    requiresInsurance?: boolean | undefined;
    requiresCouponCode?: boolean | undefined;
    couponCode?: string | undefined;
    patientCategories?: string[] | undefined;
}>, {
    value: number;
    name: string;
    ruleType: "PERCENTAGE_DISCOUNT" | "FIXED_DISCOUNT" | "FIXED_PRICE" | "PERCENTAGE_MARKUP" | "FIXED_MARKUP" | "TIERED_PRICING" | "BUNDLE_DISCOUNT";
    priority: number;
    isActive: boolean;
    applicableTo: "SERVICE" | "PROCEDURE" | "PRODUCT" | "CATEGORY" | "ALL";
    validFrom: string;
    requiresInsurance: boolean;
    requiresCouponCode: boolean;
    createdBy: string;
    description?: string | undefined;
    clinicIds?: string[] | undefined;
    targetIds?: string[] | undefined;
    validTo?: string | undefined;
    minQuantity?: number | undefined;
    maxQuantity?: number | undefined;
    couponCode?: string | undefined;
    patientCategories?: string[] | undefined;
}, {
    value: number;
    name: string;
    ruleType: "PERCENTAGE_DISCOUNT" | "FIXED_DISCOUNT" | "FIXED_PRICE" | "PERCENTAGE_MARKUP" | "FIXED_MARKUP" | "TIERED_PRICING" | "BUNDLE_DISCOUNT";
    applicableTo: "SERVICE" | "PROCEDURE" | "PRODUCT" | "CATEGORY" | "ALL";
    validFrom: string;
    createdBy: string;
    description?: string | undefined;
    priority?: number | undefined;
    clinicIds?: string[] | undefined;
    isActive?: boolean | undefined;
    targetIds?: string[] | undefined;
    validTo?: string | undefined;
    minQuantity?: number | undefined;
    maxQuantity?: number | undefined;
    requiresInsurance?: boolean | undefined;
    requiresCouponCode?: boolean | undefined;
    couponCode?: string | undefined;
    patientCategories?: string[] | undefined;
}>, {
    value: number;
    name: string;
    ruleType: "PERCENTAGE_DISCOUNT" | "FIXED_DISCOUNT" | "FIXED_PRICE" | "PERCENTAGE_MARKUP" | "FIXED_MARKUP" | "TIERED_PRICING" | "BUNDLE_DISCOUNT";
    priority: number;
    isActive: boolean;
    applicableTo: "SERVICE" | "PROCEDURE" | "PRODUCT" | "CATEGORY" | "ALL";
    validFrom: string;
    requiresInsurance: boolean;
    requiresCouponCode: boolean;
    createdBy: string;
    description?: string | undefined;
    clinicIds?: string[] | undefined;
    targetIds?: string[] | undefined;
    validTo?: string | undefined;
    minQuantity?: number | undefined;
    maxQuantity?: number | undefined;
    couponCode?: string | undefined;
    patientCategories?: string[] | undefined;
}, {
    value: number;
    name: string;
    ruleType: "PERCENTAGE_DISCOUNT" | "FIXED_DISCOUNT" | "FIXED_PRICE" | "PERCENTAGE_MARKUP" | "FIXED_MARKUP" | "TIERED_PRICING" | "BUNDLE_DISCOUNT";
    applicableTo: "SERVICE" | "PROCEDURE" | "PRODUCT" | "CATEGORY" | "ALL";
    validFrom: string;
    createdBy: string;
    description?: string | undefined;
    priority?: number | undefined;
    clinicIds?: string[] | undefined;
    isActive?: boolean | undefined;
    targetIds?: string[] | undefined;
    validTo?: string | undefined;
    minQuantity?: number | undefined;
    maxQuantity?: number | undefined;
    requiresInsurance?: boolean | undefined;
    requiresCouponCode?: boolean | undefined;
    couponCode?: string | undefined;
    patientCategories?: string[] | undefined;
}>, {
    value: number;
    name: string;
    ruleType: "PERCENTAGE_DISCOUNT" | "FIXED_DISCOUNT" | "FIXED_PRICE" | "PERCENTAGE_MARKUP" | "FIXED_MARKUP" | "TIERED_PRICING" | "BUNDLE_DISCOUNT";
    priority: number;
    isActive: boolean;
    applicableTo: "SERVICE" | "PROCEDURE" | "PRODUCT" | "CATEGORY" | "ALL";
    validFrom: string;
    requiresInsurance: boolean;
    requiresCouponCode: boolean;
    createdBy: string;
    description?: string | undefined;
    clinicIds?: string[] | undefined;
    targetIds?: string[] | undefined;
    validTo?: string | undefined;
    minQuantity?: number | undefined;
    maxQuantity?: number | undefined;
    couponCode?: string | undefined;
    patientCategories?: string[] | undefined;
}, {
    value: number;
    name: string;
    ruleType: "PERCENTAGE_DISCOUNT" | "FIXED_DISCOUNT" | "FIXED_PRICE" | "PERCENTAGE_MARKUP" | "FIXED_MARKUP" | "TIERED_PRICING" | "BUNDLE_DISCOUNT";
    applicableTo: "SERVICE" | "PROCEDURE" | "PRODUCT" | "CATEGORY" | "ALL";
    validFrom: string;
    createdBy: string;
    description?: string | undefined;
    priority?: number | undefined;
    clinicIds?: string[] | undefined;
    isActive?: boolean | undefined;
    targetIds?: string[] | undefined;
    validTo?: string | undefined;
    minQuantity?: number | undefined;
    maxQuantity?: number | undefined;
    requiresInsurance?: boolean | undefined;
    requiresCouponCode?: boolean | undefined;
    couponCode?: string | undefined;
    patientCategories?: string[] | undefined;
}>, {
    value: number;
    name: string;
    ruleType: "PERCENTAGE_DISCOUNT" | "FIXED_DISCOUNT" | "FIXED_PRICE" | "PERCENTAGE_MARKUP" | "FIXED_MARKUP" | "TIERED_PRICING" | "BUNDLE_DISCOUNT";
    priority: number;
    isActive: boolean;
    applicableTo: "SERVICE" | "PROCEDURE" | "PRODUCT" | "CATEGORY" | "ALL";
    validFrom: string;
    requiresInsurance: boolean;
    requiresCouponCode: boolean;
    createdBy: string;
    description?: string | undefined;
    clinicIds?: string[] | undefined;
    targetIds?: string[] | undefined;
    validTo?: string | undefined;
    minQuantity?: number | undefined;
    maxQuantity?: number | undefined;
    couponCode?: string | undefined;
    patientCategories?: string[] | undefined;
}, {
    value: number;
    name: string;
    ruleType: "PERCENTAGE_DISCOUNT" | "FIXED_DISCOUNT" | "FIXED_PRICE" | "PERCENTAGE_MARKUP" | "FIXED_MARKUP" | "TIERED_PRICING" | "BUNDLE_DISCOUNT";
    applicableTo: "SERVICE" | "PROCEDURE" | "PRODUCT" | "CATEGORY" | "ALL";
    validFrom: string;
    createdBy: string;
    description?: string | undefined;
    priority?: number | undefined;
    clinicIds?: string[] | undefined;
    isActive?: boolean | undefined;
    targetIds?: string[] | undefined;
    validTo?: string | undefined;
    minQuantity?: number | undefined;
    maxQuantity?: number | undefined;
    requiresInsurance?: boolean | undefined;
    requiresCouponCode?: boolean | undefined;
    couponCode?: string | undefined;
    patientCategories?: string[] | undefined;
}>;
export declare const ApplyPriceRuleDtoSchema: z.ZodObject<{
    procedureId: z.ZodOptional<z.ZodString>;
    productId: z.ZodOptional<z.ZodString>;
    serviceId: z.ZodOptional<z.ZodString>;
    quantity: z.ZodDefault<z.ZodNumber>;
    patientId: z.ZodOptional<z.ZodString>;
    couponCode: z.ZodOptional<z.ZodString>;
    applyDate: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
}, "strip", z.ZodTypeAny, {
    quantity: number;
    patientId?: string | undefined;
    procedureId?: string | undefined;
    couponCode?: string | undefined;
    productId?: string | undefined;
    serviceId?: string | undefined;
    applyDate?: string | undefined;
}, {
    quantity?: number | undefined;
    patientId?: string | undefined;
    procedureId?: string | undefined;
    couponCode?: string | undefined;
    productId?: string | undefined;
    serviceId?: string | undefined;
    applyDate?: string | undefined;
}>;
export declare const CreateTaxRateDtoSchema: z.ZodObject<{
    name: z.ZodString;
    rate: z.ZodNumber;
    jurisdictionId: z.ZodOptional<z.ZodString>;
    jurisdictionCode: z.ZodOptional<z.ZodString>;
    applicableTo: z.ZodDefault<z.ZodEnum<["ALL", "PRODUCTS", "SERVICES", "MEDICAL", "DENTAL"]>>;
    isDefault: z.ZodDefault<z.ZodBoolean>;
    validFrom: z.ZodEffects<z.ZodString, string, string>;
    validTo: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    description: z.ZodOptional<z.ZodString>;
    isActive: z.ZodDefault<z.ZodBoolean>;
    createdBy: z.ZodString;
}, "strip", z.ZodTypeAny, {
    name: string;
    isActive: boolean;
    applicableTo: "ALL" | "PRODUCTS" | "SERVICES" | "MEDICAL" | "DENTAL";
    validFrom: string;
    createdBy: string;
    rate: number;
    isDefault: boolean;
    description?: string | undefined;
    validTo?: string | undefined;
    jurisdictionId?: string | undefined;
    jurisdictionCode?: string | undefined;
}, {
    name: string;
    validFrom: string;
    createdBy: string;
    rate: number;
    description?: string | undefined;
    isActive?: boolean | undefined;
    applicableTo?: "ALL" | "PRODUCTS" | "SERVICES" | "MEDICAL" | "DENTAL" | undefined;
    validTo?: string | undefined;
    jurisdictionId?: string | undefined;
    jurisdictionCode?: string | undefined;
    isDefault?: boolean | undefined;
}>;
export declare const QueryPatientBalanceDtoSchema: z.ZodObject<{
    patientId: z.ZodString;
    asOfDate: z.ZodOptional<z.ZodEffects<z.ZodString, string, string>>;
    includeProjections: z.ZodDefault<z.ZodBoolean>;
    currency: z.ZodOptional<z.ZodNativeEnum<typeof CurrencyCode>>;
}, "strip", z.ZodTypeAny, {
    patientId: string;
    includeProjections: boolean;
    currency?: CurrencyCode | undefined;
    asOfDate?: string | undefined;
}, {
    patientId: string;
    currency?: CurrencyCode | undefined;
    asOfDate?: string | undefined;
    includeProjections?: boolean | undefined;
}>;
export type MoneyAmount = z.infer<typeof MoneyAmountSchema>;
export type PositiveMoneyAmount = z.infer<typeof PositiveMoneyAmountSchema>;
export type NonNegativeMoneyAmount = z.infer<typeof NonNegativeMoneyAmountSchema>;
export type TaxRate = z.infer<typeof TaxRateSchema>;
export type InvoiceStatus = z.infer<typeof InvoiceStatusSchema>;
export type ItemType = z.infer<typeof ItemTypeSchema>;
export type CreateInvoiceDto = z.infer<typeof CreateInvoiceDtoSchema>;
export type UpdateInvoiceStatusDto = z.infer<typeof UpdateInvoiceStatusDtoSchema>;
export type QueryInvoicesDto = z.infer<typeof QueryInvoicesDtoSchema>;
export type AddInvoiceItemDto = z.infer<typeof AddInvoiceItemDtoSchema>;
export type UpdateInvoiceItemDto = z.infer<typeof UpdateInvoiceItemDtoSchema>;
export type PaymentMethod = z.infer<typeof PaymentMethodSchema>;
export type RecordPaymentDto = z.infer<typeof RecordPaymentDtoSchema>;
export type SplitPaymentItem = z.infer<typeof SplitPaymentItemSchema>;
export type RecordSplitPaymentDto = z.infer<typeof RecordSplitPaymentDtoSchema>;
export type RefundPaymentDto = z.infer<typeof RefundPaymentDtoSchema>;
export type ClaimStatus = z.infer<typeof ClaimStatusSchema>;
export type CreateInsuranceClaimDto = z.infer<typeof CreateInsuranceClaimDtoSchema>;
export type UpdateClaimStatusDto = z.infer<typeof UpdateClaimStatusDtoSchema>;
export type RuleType = z.infer<typeof RuleTypeSchema>;
export type CreatePriceRuleDto = z.infer<typeof CreatePriceRuleDtoSchema>;
export type ApplyPriceRuleDto = z.infer<typeof ApplyPriceRuleDtoSchema>;
export type CreateTaxRateDto = z.infer<typeof CreateTaxRateDtoSchema>;
export type QueryPatientBalanceDto = z.infer<typeof QueryPatientBalanceDtoSchema>;
