"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LicenseForbiddenException = exports.LicenseValidatorService = exports.getSubscriptionStatus = exports.isSubscriptionExpired = exports.isTrialUser = exports.getMissingModules = exports.canAccessModule = exports.getPremiumModules = exports.getCoreModules = exports.hasOnlyCoreModules = exports.hasPremiumAccess = exports.isInGracePeriodSimple = exports.isSubscriptionActive = exports.getAvailableModules = exports.hasAllModules = exports.hasAnyModule = exports.hasModule = exports.dependsOn = exports.validateModuleDependencies = exports.getDependencyErrorMessage = exports.areDependenciesSatisfied = exports.getAllMissingDependencies = exports.getMissingDependencies = exports.hasModuleDependencies = exports.getAllModuleDependencies = exports.getModuleDependencies = exports.getGracePeriodStatusMessage = exports.calculateGracePeriodEnd = exports.canPerformWriteOperation = exports.canPerformOperation = exports.isWriteOperation = exports.isReadOperation = exports.isGracePeriodExpiringSoon = exports.getGracePeriodDaysRemaining = exports.isInGracePeriod = exports.ALL_MODULES = exports.PREMIUM_MODULES = exports.CORE_MODULES = exports.WRITE_METHODS = exports.READ_METHODS = exports.GRACE_PERIOD_DAYS = void 0;
var license_constants_1 = require("./license.constants");
Object.defineProperty(exports, "GRACE_PERIOD_DAYS", { enumerable: true, get: function () { return license_constants_1.GRACE_PERIOD_DAYS; } });
Object.defineProperty(exports, "READ_METHODS", { enumerable: true, get: function () { return license_constants_1.READ_METHODS; } });
Object.defineProperty(exports, "WRITE_METHODS", { enumerable: true, get: function () { return license_constants_1.WRITE_METHODS; } });
Object.defineProperty(exports, "CORE_MODULES", { enumerable: true, get: function () { return license_constants_1.CORE_MODULES; } });
Object.defineProperty(exports, "PREMIUM_MODULES", { enumerable: true, get: function () { return license_constants_1.PREMIUM_MODULES; } });
Object.defineProperty(exports, "ALL_MODULES", { enumerable: true, get: function () { return license_constants_1.ALL_MODULES; } });
var grace_period_helper_1 = require("./grace-period.helper");
Object.defineProperty(exports, "isInGracePeriod", { enumerable: true, get: function () { return grace_period_helper_1.isInGracePeriod; } });
Object.defineProperty(exports, "getGracePeriodDaysRemaining", { enumerable: true, get: function () { return grace_period_helper_1.getGracePeriodDaysRemaining; } });
Object.defineProperty(exports, "isGracePeriodExpiringSoon", { enumerable: true, get: function () { return grace_period_helper_1.isGracePeriodExpiringSoon; } });
Object.defineProperty(exports, "isReadOperation", { enumerable: true, get: function () { return grace_period_helper_1.isReadOperation; } });
Object.defineProperty(exports, "isWriteOperation", { enumerable: true, get: function () { return grace_period_helper_1.isWriteOperation; } });
Object.defineProperty(exports, "canPerformOperation", { enumerable: true, get: function () { return grace_period_helper_1.canPerformOperation; } });
Object.defineProperty(exports, "canPerformWriteOperation", { enumerable: true, get: function () { return grace_period_helper_1.canPerformWriteOperation; } });
Object.defineProperty(exports, "calculateGracePeriodEnd", { enumerable: true, get: function () { return grace_period_helper_1.calculateGracePeriodEnd; } });
Object.defineProperty(exports, "getGracePeriodStatusMessage", { enumerable: true, get: function () { return grace_period_helper_1.getGracePeriodStatusMessage; } });
var module_dependencies_helper_1 = require("./module-dependencies.helper");
Object.defineProperty(exports, "getModuleDependencies", { enumerable: true, get: function () { return module_dependencies_helper_1.getModuleDependencies; } });
Object.defineProperty(exports, "getAllModuleDependencies", { enumerable: true, get: function () { return module_dependencies_helper_1.getAllModuleDependencies; } });
Object.defineProperty(exports, "hasModuleDependencies", { enumerable: true, get: function () { return module_dependencies_helper_1.hasModuleDependencies; } });
Object.defineProperty(exports, "getMissingDependencies", { enumerable: true, get: function () { return module_dependencies_helper_1.getMissingDependencies; } });
Object.defineProperty(exports, "getAllMissingDependencies", { enumerable: true, get: function () { return module_dependencies_helper_1.getAllMissingDependencies; } });
Object.defineProperty(exports, "areDependenciesSatisfied", { enumerable: true, get: function () { return module_dependencies_helper_1.areDependenciesSatisfied; } });
Object.defineProperty(exports, "getDependencyErrorMessage", { enumerable: true, get: function () { return module_dependencies_helper_1.getDependencyErrorMessage; } });
Object.defineProperty(exports, "validateModuleDependencies", { enumerable: true, get: function () { return module_dependencies_helper_1.validateModuleDependencies; } });
Object.defineProperty(exports, "dependsOn", { enumerable: true, get: function () { return module_dependencies_helper_1.dependsOn; } });
var license_validator_functions_1 = require("./license-validator.functions");
Object.defineProperty(exports, "hasModule", { enumerable: true, get: function () { return license_validator_functions_1.hasModule; } });
Object.defineProperty(exports, "hasAnyModule", { enumerable: true, get: function () { return license_validator_functions_1.hasAnyModule; } });
Object.defineProperty(exports, "hasAllModules", { enumerable: true, get: function () { return license_validator_functions_1.hasAllModules; } });
Object.defineProperty(exports, "getAvailableModules", { enumerable: true, get: function () { return license_validator_functions_1.getAvailableModules; } });
Object.defineProperty(exports, "isSubscriptionActive", { enumerable: true, get: function () { return license_validator_functions_1.isSubscriptionActive; } });
Object.defineProperty(exports, "isInGracePeriodSimple", { enumerable: true, get: function () { return license_validator_functions_1.isInGracePeriodSimple; } });
Object.defineProperty(exports, "hasPremiumAccess", { enumerable: true, get: function () { return license_validator_functions_1.hasPremiumAccess; } });
Object.defineProperty(exports, "hasOnlyCoreModules", { enumerable: true, get: function () { return license_validator_functions_1.hasOnlyCoreModules; } });
Object.defineProperty(exports, "getCoreModules", { enumerable: true, get: function () { return license_validator_functions_1.getCoreModules; } });
Object.defineProperty(exports, "getPremiumModules", { enumerable: true, get: function () { return license_validator_functions_1.getPremiumModules; } });
Object.defineProperty(exports, "canAccessModule", { enumerable: true, get: function () { return license_validator_functions_1.canAccessModule; } });
Object.defineProperty(exports, "getMissingModules", { enumerable: true, get: function () { return license_validator_functions_1.getMissingModules; } });
Object.defineProperty(exports, "isTrialUser", { enumerable: true, get: function () { return license_validator_functions_1.isTrialUser; } });
Object.defineProperty(exports, "isSubscriptionExpired", { enumerable: true, get: function () { return license_validator_functions_1.isSubscriptionExpired; } });
Object.defineProperty(exports, "getSubscriptionStatus", { enumerable: true, get: function () { return license_validator_functions_1.getSubscriptionStatus; } });
var license_validator_service_1 = require("./license-validator.service");
Object.defineProperty(exports, "LicenseValidatorService", { enumerable: true, get: function () { return license_validator_service_1.LicenseValidatorService; } });
Object.defineProperty(exports, "LicenseForbiddenException", { enumerable: true, get: function () { return license_validator_service_1.LicenseForbiddenException; } });
//# sourceMappingURL=index.js.map