import { CurrentUser } from '../context/current-user';
import { ModuleCode, SubscriptionStatus } from '../jwt/jwt-payload.types';
export declare function hasModule(user: CurrentUser, moduleCode: ModuleCode): boolean;
export declare function hasAnyModule(user: CurrentUser, moduleCodes: ModuleCode[]): boolean;
export declare function hasAllModules(user: CurrentUser, moduleCodes: ModuleCode[]): boolean;
export declare function getAvailableModules(user: CurrentUser): readonly ModuleCode[];
export declare function isSubscriptionActive(user: CurrentUser): boolean;
export declare function isInGracePeriodSimple(user: CurrentUser): boolean;
export declare function hasPremiumAccess(user: CurrentUser): boolean;
export declare function hasOnlyCoreModules(user: CurrentUser): boolean;
export declare function getCoreModules(user: CurrentUser): ModuleCode[];
export declare function getPremiumModules(user: CurrentUser): ModuleCode[];
export declare function canAccessModule(user: CurrentUser, moduleCode: ModuleCode): boolean;
export declare function getMissingModules(user: CurrentUser, requiredModules: ModuleCode[]): ModuleCode[];
export declare function isTrialUser(user: CurrentUser): boolean;
export declare function isSubscriptionExpired(user: CurrentUser): boolean;
export declare function getSubscriptionStatus(user: CurrentUser): SubscriptionStatus | null;
