"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConsentType = exports.DeliveryProvider = exports.DeliveryStatus = exports.AutomationActionType = exports.AutomationTriggerType = exports.NpsCategory = exports.FeedbackSentiment = exports.FeedbackCategory = exports.LoyaltyRedemptionType = exports.LoyaltyAccrualSource = exports.LoyaltyTransactionType = exports.LoyaltyTier = exports.ReferralRewardType = exports.ReferralStatus = exports.SegmentType = exports.SegmentRuleGroupOperator = exports.SegmentRuleOperator = exports.SegmentRuleField = exports.RecurrenceFrequency = exports.CampaignScheduleType = exports.CampaignStatus = exports.CampaignChannel = void 0;
var marketing_types_1 = require("./marketing.types");
Object.defineProperty(exports, "CampaignChannel", { enumerable: true, get: function () { return marketing_types_1.CampaignChannel; } });
Object.defineProperty(exports, "CampaignStatus", { enumerable: true, get: function () { return marketing_types_1.CampaignStatus; } });
Object.defineProperty(exports, "CampaignScheduleType", { enumerable: true, get: function () { return marketing_types_1.CampaignScheduleType; } });
Object.defineProperty(exports, "RecurrenceFrequency", { enumerable: true, get: function () { return marketing_types_1.RecurrenceFrequency; } });
var marketing_types_2 = require("./marketing.types");
Object.defineProperty(exports, "SegmentRuleField", { enumerable: true, get: function () { return marketing_types_2.SegmentRuleField; } });
Object.defineProperty(exports, "SegmentRuleOperator", { enumerable: true, get: function () { return marketing_types_2.SegmentRuleOperator; } });
Object.defineProperty(exports, "SegmentRuleGroupOperator", { enumerable: true, get: function () { return marketing_types_2.SegmentRuleGroupOperator; } });
Object.defineProperty(exports, "SegmentType", { enumerable: true, get: function () { return marketing_types_2.SegmentType; } });
var marketing_types_3 = require("./marketing.types");
Object.defineProperty(exports, "ReferralStatus", { enumerable: true, get: function () { return marketing_types_3.ReferralStatus; } });
Object.defineProperty(exports, "ReferralRewardType", { enumerable: true, get: function () { return marketing_types_3.ReferralRewardType; } });
var marketing_types_4 = require("./marketing.types");
Object.defineProperty(exports, "LoyaltyTier", { enumerable: true, get: function () { return marketing_types_4.LoyaltyTier; } });
Object.defineProperty(exports, "LoyaltyTransactionType", { enumerable: true, get: function () { return marketing_types_4.LoyaltyTransactionType; } });
Object.defineProperty(exports, "LoyaltyAccrualSource", { enumerable: true, get: function () { return marketing_types_4.LoyaltyAccrualSource; } });
Object.defineProperty(exports, "LoyaltyRedemptionType", { enumerable: true, get: function () { return marketing_types_4.LoyaltyRedemptionType; } });
var marketing_types_5 = require("./marketing.types");
Object.defineProperty(exports, "FeedbackCategory", { enumerable: true, get: function () { return marketing_types_5.FeedbackCategory; } });
Object.defineProperty(exports, "FeedbackSentiment", { enumerable: true, get: function () { return marketing_types_5.FeedbackSentiment; } });
Object.defineProperty(exports, "NpsCategory", { enumerable: true, get: function () { return marketing_types_5.NpsCategory; } });
var marketing_types_6 = require("./marketing.types");
Object.defineProperty(exports, "AutomationTriggerType", { enumerable: true, get: function () { return marketing_types_6.AutomationTriggerType; } });
Object.defineProperty(exports, "AutomationActionType", { enumerable: true, get: function () { return marketing_types_6.AutomationActionType; } });
var marketing_types_7 = require("./marketing.types");
Object.defineProperty(exports, "DeliveryStatus", { enumerable: true, get: function () { return marketing_types_7.DeliveryStatus; } });
Object.defineProperty(exports, "DeliveryProvider", { enumerable: true, get: function () { return marketing_types_7.DeliveryProvider; } });
Object.defineProperty(exports, "ConsentType", { enumerable: true, get: function () { return marketing_types_7.ConsentType; } });
//# sourceMappingURL=index.js.map