export type { CampaignId, SegmentId, ReferralId, LoyaltyAccountId, LoyaltyTransactionId, FeedbackId, NpsScoreId, AutomationRuleId, DeliveryLogId, CampaignTemplateId, AutomationExecutionId, } from './marketing.types';
export { CampaignChannel, CampaignStatus, CampaignScheduleType, RecurrenceFrequency, } from './marketing.types';
export type { CampaignSchedule, RecurrenceRule, CampaignTemplate, CampaignAttachment, CampaignMetrics, Campaign, } from './marketing.types';
export { SegmentRuleField, SegmentRuleOperator, SegmentRuleGroupOperator, SegmentType, } from './marketing.types';
export type { SegmentRule, SegmentRuleGroup, Segment, } from './marketing.types';
export { ReferralStatus, ReferralRewardType, } from './marketing.types';
export type { ReferralReward, Referral, } from './marketing.types';
export { LoyaltyTier, LoyaltyTransactionType, LoyaltyAccrualSource, LoyaltyRedemptionType, } from './marketing.types';
export type { LoyaltyAccount, LoyaltyTransaction, LoyaltyAccrualRule, } from './marketing.types';
export { FeedbackCategory, FeedbackSentiment, NpsCategory, } from './marketing.types';
export type { FeedbackRecord, NpsScore, NpsAggregate, } from './marketing.types';
export { AutomationTriggerType, AutomationActionType, } from './marketing.types';
export type { AutomationCondition, AutomationAction, AutomationActionParams, SendCampaignParams, SendMessageParams, AccrueLoyaltyPointsParams, CreateReferralParams, SendNotificationParams, AddToSegmentParams, RemoveFromSegmentParams, CreateTaskParams, UpdatePatientTagsParams, SendWebhookParams, WaitParams, AutomationRule, AutomationExecution, } from './marketing.types';
export { DeliveryStatus, DeliveryProvider, ConsentType, } from './marketing.types';
export type { DeliveryLog, CommunicationPreference, } from './marketing.types';
export type { MarketingOpportunity, ChurnRiskScore, SentimentAnalysisResult, } from './marketing.types';
